// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/sso/sso.proto

package sso

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_sso_sso_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_sso_sso_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_api_sso_sso_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetAuthConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthConfigRequest) Reset() {
	*x = GetAuthConfigRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthConfigRequest) ProtoMessage() {}

func (x *GetAuthConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthConfigRequest.ProtoReflect.Descriptor instead.
func (*GetAuthConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{6}
}

type OIDCProviderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OIDCProviderData) Reset() {
	*x = OIDCProviderData{}
	mi := &file_api_sso_sso_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCProviderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCProviderData) ProtoMessage() {}

func (x *OIDCProviderData) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCProviderData.ProtoReflect.Descriptor instead.
func (*OIDCProviderData) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{7}
}

func (x *OIDCProviderData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAuthConfigResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LocalLoginEnabled    bool                   `protobuf:"varint,1,opt,name=local_login_enabled,json=localLoginEnabled,proto3" json:"local_login_enabled,omitempty"`
	LocalRegisterEnabled bool                   `protobuf:"varint,2,opt,name=local_register_enabled,json=localRegisterEnabled,proto3" json:"local_register_enabled,omitempty"`
	OidcProviders        []*OIDCProviderData    `protobuf:"bytes,3,rep,name=oidc_providers,json=oidcProviders,proto3" json:"oidc_providers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetAuthConfigResponse) Reset() {
	*x = GetAuthConfigResponse{}
	mi := &file_api_sso_sso_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthConfigResponse) ProtoMessage() {}

func (x *GetAuthConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthConfigResponse.ProtoReflect.Descriptor instead.
func (*GetAuthConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{8}
}

func (x *GetAuthConfigResponse) GetLocalLoginEnabled() bool {
	if x != nil {
		return x.LocalLoginEnabled
	}
	return false
}

func (x *GetAuthConfigResponse) GetLocalRegisterEnabled() bool {
	if x != nil {
		return x.LocalRegisterEnabled
	}
	return false
}

func (x *GetAuthConfigResponse) GetOidcProviders() []*OIDCProviderData {
	if x != nil {
		return x.OidcProviders
	}
	return nil
}

type StartOIDCLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	RedirectAfter string                 `protobuf:"bytes,2,opt,name=redirect_after,json=redirectAfter,proto3" json:"redirect_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOIDCLoginRequest) Reset() {
	*x = StartOIDCLoginRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOIDCLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOIDCLoginRequest) ProtoMessage() {}

func (x *StartOIDCLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOIDCLoginRequest.ProtoReflect.Descriptor instead.
func (*StartOIDCLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{9}
}

func (x *StartOIDCLoginRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StartOIDCLoginRequest) GetRedirectAfter() string {
	if x != nil {
		return x.RedirectAfter
	}
	return ""
}

type StartOIDCLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	StateBinding  string                 `protobuf:"bytes,2,opt,name=state_binding,json=stateBinding,proto3" json:"state_binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOIDCLoginResponse) Reset() {
	*x = StartOIDCLoginResponse{}
	mi := &file_api_sso_sso_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOIDCLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOIDCLoginResponse) ProtoMessage() {}

func (x *StartOIDCLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOIDCLoginResponse.ProtoReflect.Descriptor instead.
func (*StartOIDCLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{10}
}

func (x *StartOIDCLoginResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *StartOIDCLoginResponse) GetStateBinding() string {
	if x != nil {
		return x.StateBinding
	}
	return ""
}

type CompleteOIDCCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	StateBinding  string                 `protobuf:"bytes,4,opt,name=state_binding,json=stateBinding,proto3" json:"state_binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOIDCCallbackRequest) Reset() {
	*x = CompleteOIDCCallbackRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOIDCCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOIDCCallbackRequest) ProtoMessage() {}

func (x *CompleteOIDCCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOIDCCallbackRequest.ProtoReflect.Descriptor instead.
func (*CompleteOIDCCallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteOIDCCallbackRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CompleteOIDCCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteOIDCCallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CompleteOIDCCallbackRequest) GetStateBinding() string {
	if x != nil {
		return x.StateBinding
	}
	return ""
}

type CompleteOIDCCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RedirectAfter string                 `protobuf:"bytes,3,opt,name=redirect_after,json=redirectAfter,proto3" json:"redirect_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOIDCCallbackResponse) Reset() {
	*x = CompleteOIDCCallbackResponse{}
	mi := &file_api_sso_sso_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOIDCCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOIDCCallbackResponse) ProtoMessage() {}

func (x *CompleteOIDCCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOIDCCallbackResponse.ProtoReflect.Descriptor instead.
func (*CompleteOIDCCallbackResponse) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteOIDCCallbackResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CompleteOIDCCallbackResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CompleteOIDCCallbackResponse) GetRedirectAfter() string {
	if x != nil {
		return x.RedirectAfter
	}
	return ""
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Permission    string                 `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{14}
}

func (x *CheckPermissionRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CheckPermissionRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	User          *UserData              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_api_sso_sso_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{15}
}

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckPermissionResponse) GetUser() *UserData {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{17}
}

func (x *UserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BatchGetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUsersRequest) Reset() {
	*x = BatchGetUsersRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersRequest) ProtoMessage() {}

func (x *BatchGetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersRequest.ProtoReflect.Descriptor instead.
func (*BatchGetUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{18}
}

func (x *BatchGetUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	QuotaRamMb    int64                  `protobuf:"varint,5,opt,name=quota_ram_mb,json=quotaRamMb,proto3" json:"quota_ram_mb,omitempty"`
	QuotaDiskMb   int64                  `protobuf:"varint,6,opt,name=quota_disk_mb,json=quotaDiskMb,proto3" json:"quota_disk_mb,omitempty"`
	QuotaCpu      float64                `protobuf:"fixed64,7,opt,name=quota_cpu,json=quotaCpu,proto3" json:"quota_cpu,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_api_sso_sso_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{19}
}

func (x *UserData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserData) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserData) GetQuotaRamMb() int64 {
	if x != nil {
		return x.QuotaRamMb
	}
	return 0
}

func (x *UserData) GetQuotaDiskMb() int64 {
	if x != nil {
		return x.QuotaDiskMb
	}
	return 0
}

func (x *UserData) GetQuotaCpu() float64 {
	if x != nil {
		return x.QuotaCpu
	}
	return 0
}

func (x *UserData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BatchGetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserData            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUsersResponse) Reset() {
	*x = BatchGetUsersResponse{}
	mi := &file_api_sso_sso_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersResponse) ProtoMessage() {}

func (x *BatchGetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersResponse.ProtoReflect.Descriptor instead.
func (*BatchGetUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{20}
}

func (x *BatchGetUsersResponse) GetUsers() []*UserData {
	if x != nil {
		return x.Users
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{21}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserData            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_api_sso_sso_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{22}
}

func (x *ListUsersResponse) GetUsers() []*UserData {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	QuotaCpu      float64                `protobuf:"fixed64,6,opt,name=quota_cpu,json=quotaCpu,proto3" json:"quota_cpu,omitempty"`
	QuotaRamMb    int64                  `protobuf:"varint,7,opt,name=quota_ram_mb,json=quotaRamMb,proto3" json:"quota_ram_mb,omitempty"`
	QuotaDiskMb   int64                  `protobuf:"varint,8,opt,name=quota_disk_mb,json=quotaDiskMb,proto3" json:"quota_disk_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{23}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateUserRequest) GetQuotaCpu() float64 {
	if x != nil {
		return x.QuotaCpu
	}
	return 0
}

func (x *CreateUserRequest) GetQuotaRamMb() int64 {
	if x != nil {
		return x.QuotaRamMb
	}
	return 0
}

func (x *CreateUserRequest) GetQuotaDiskMb() int64 {
	if x != nil {
		return x.QuotaDiskMb
	}
	return 0
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	QuotaCpu      float64                `protobuf:"fixed64,7,opt,name=quota_cpu,json=quotaCpu,proto3" json:"quota_cpu,omitempty"`
	QuotaRamMb    int64                  `protobuf:"varint,8,opt,name=quota_ram_mb,json=quotaRamMb,proto3" json:"quota_ram_mb,omitempty"`
	QuotaDiskMb   int64                  `protobuf:"varint,9,opt,name=quota_disk_mb,json=quotaDiskMb,proto3" json:"quota_disk_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_sso_sso_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sso_sso_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_sso_sso_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UpdateUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateUserRequest) GetQuotaCpu() float64 {
	if x != nil {
		return x.QuotaCpu
	}
	return 0
}

func (x *UpdateUserRequest) GetQuotaRamMb() int64 {
	if x != nil {
		return x.QuotaRamMb
	}
	return 0
}

func (x *UpdateUserRequest) GetQuotaDiskMb() int64 {
	if x != nil {
		return x.QuotaDiskMb
	}
	return 0
}

var File_api_sso_sso_proto protoreflect.FileDescriptor

const file_api_sso_sso_proto_rawDesc = "" +
	"\n" +
	"\x11api/sso/sso.proto\x12\x03sso\"_\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"W\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"Y\n" +
	"\x0fRefreshResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\x16\n" +
	"\x14GetAuthConfigRequest\"&\n" +
	"\x10OIDCProviderData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xbb\x01\n" +
	"\x15GetAuthConfigResponse\x12.\n" +
	"\x13local_login_enabled\x18\x01 \x01(\bR\x11localLoginEnabled\x124\n" +
	"\x16local_register_enabled\x18\x02 \x01(\bR\x14localRegisterEnabled\x12<\n" +
	"\x0eoidc_providers\x18\x03 \x03(\v2\x15.sso.OIDCProviderDataR\roidcProviders\"Z\n" +
	"\x15StartOIDCLoginRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12%\n" +
	"\x0eredirect_after\x18\x02 \x01(\tR\rredirectAfter\"X\n" +
	"\x16StartOIDCLoginResponse\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\x12#\n" +
	"\rstate_binding\x18\x02 \x01(\tR\fstateBinding\"\x88\x01\n" +
	"\x1bCompleteOIDCCallbackRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12#\n" +
	"\rstate_binding\x18\x04 \x01(\tR\fstateBinding\"\x8d\x01\n" +
	"\x1cCompleteOIDCCallbackResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12%\n" +
	"\x0eredirect_after\x18\x03 \x01(\tR\rredirectAfter\"7\n" +
	"\x12VerifyTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"[\n" +
	"\x16CheckPermissionRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x01(\tR\n" +
	"permission\"V\n" +
	"\x17CheckPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12!\n" +
	"\x04user\x18\x02 \x01(\v2\r.sso.UserDataR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"(\n" +
	"\rUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"1\n" +
	"\x14BatchGetUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xe4\x01\n" +
	"\bUserData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12 \n" +
	"\fquota_ram_mb\x18\x05 \x01(\x03R\n" +
	"quotaRamMb\x12\"\n" +
	"\rquota_disk_mb\x18\x06 \x01(\x03R\vquotaDiskMb\x12\x1b\n" +
	"\tquota_cpu\x18\a \x01(\x01R\bquotaCpu\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"<\n" +
	"\x15BatchGetUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.sso.UserDataR\x05users\"<\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"Y\n" +
	"\x11ListUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.sso.UserDataR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xf0\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tquota_cpu\x18\x06 \x01(\x01R\bquotaCpu\x12 \n" +
	"\fquota_ram_mb\x18\a \x01(\x03R\n" +
	"quotaRamMb\x12\"\n" +
	"\rquota_disk_mb\x18\b \x01(\x03R\vquotaDiskMb\"\x89\x02\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1b\n" +
	"\tquota_cpu\x18\a \x01(\x01R\bquotaCpu\x12 \n" +
	"\fquota_ram_mb\x18\b \x01(\x03R\n" +
	"quotaRamMb\x12\"\n" +
	"\rquota_disk_mb\x18\t \x01(\x03R\vquotaDiskMb2\x95\x03\n" +
	"\x04Auth\x127\n" +
	"\bRegister\x12\x14.sso.RegisterRequest\x1a\x15.sso.RegisterResponse\x12.\n" +
	"\x05Login\x12\x11.sso.LoginRequest\x1a\x12.sso.LoginResponse\x124\n" +
	"\aRefresh\x12\x13.sso.RefreshRequest\x1a\x14.sso.RefreshResponse\x12F\n" +
	"\rGetAuthConfig\x12\x19.sso.GetAuthConfigRequest\x1a\x1a.sso.GetAuthConfigResponse\x12I\n" +
	"\x0eStartOIDCLogin\x12\x1a.sso.StartOIDCLoginRequest\x1a\x1b.sso.StartOIDCLoginResponse\x12[\n" +
	"\x14CompleteOIDCCallback\x12 .sso.CompleteOIDCCallbackRequest\x1a!.sso.CompleteOIDCCallbackResponse2\x9b\x04\n" +
	"\aUserAPI\x12;\n" +
	"\x11VerifyAccessToken\x12\x17.sso.VerifyTokenRequest\x1a\r.sso.UserData\x12L\n" +
	"\x0fCheckPermission\x12\x1b.sso.CheckPermissionRequest\x1a\x1c.sso.CheckPermissionResponse\x12-\n" +
	"\aGetUser\x12\x13.sso.GetUserRequest\x1a\r.sso.UserData\x12F\n" +
	"\rBatchGetUsers\x12\x19.sso.BatchGetUsersRequest\x1a\x1a.sso.BatchGetUsersResponse\x12:\n" +
	"\tListUsers\x12\x15.sso.ListUsersRequest\x1a\x16.sso.ListUsersResponse\x123\n" +
	"\n" +
	"CreateUser\x12\x16.sso.CreateUserRequest\x1a\r.sso.UserData\x123\n" +
	"\n" +
	"UpdateUser\x12\x16.sso.UpdateUserRequest\x1a\r.sso.UserData\x123\n" +
	"\x0eDeactivateUser\x12\x12.sso.UserIDRequest\x1a\r.sso.UserData\x123\n" +
	"\x0eReactivateUser\x12\x12.sso.UserIDRequest\x1a\r.sso.UserDataBEZCgithub.com/callmerussell04/docker-cloud-manager/backend/api/sso;ssob\x06proto3"

var (
	file_api_sso_sso_proto_rawDescOnce sync.Once
	file_api_sso_sso_proto_rawDescData []byte
)

func file_api_sso_sso_proto_rawDescGZIP() []byte {
	file_api_sso_sso_proto_rawDescOnce.Do(func() {
		file_api_sso_sso_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_sso_sso_proto_rawDesc), len(file_api_sso_sso_proto_rawDesc)))
	})
	return file_api_sso_sso_proto_rawDescData
}

var file_api_sso_sso_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_sso_sso_proto_goTypes = []any{
	(*RegisterRequest)(nil),              // 0: sso.RegisterRequest
	(*RegisterResponse)(nil),             // 1: sso.RegisterResponse
	(*LoginRequest)(nil),                 // 2: sso.LoginRequest
	(*LoginResponse)(nil),                // 3: sso.LoginResponse
	(*RefreshRequest)(nil),               // 4: sso.RefreshRequest
	(*RefreshResponse)(nil),              // 5: sso.RefreshResponse
	(*GetAuthConfigRequest)(nil),         // 6: sso.GetAuthConfigRequest
	(*OIDCProviderData)(nil),             // 7: sso.OIDCProviderData
	(*GetAuthConfigResponse)(nil),        // 8: sso.GetAuthConfigResponse
	(*StartOIDCLoginRequest)(nil),        // 9: sso.StartOIDCLoginRequest
	(*StartOIDCLoginResponse)(nil),       // 10: sso.StartOIDCLoginResponse
	(*CompleteOIDCCallbackRequest)(nil),  // 11: sso.CompleteOIDCCallbackRequest
	(*CompleteOIDCCallbackResponse)(nil), // 12: sso.CompleteOIDCCallbackResponse
	(*VerifyTokenRequest)(nil),           // 13: sso.VerifyTokenRequest
	(*CheckPermissionRequest)(nil),       // 14: sso.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),      // 15: sso.CheckPermissionResponse
	(*GetUserRequest)(nil),               // 16: sso.GetUserRequest
	(*UserIDRequest)(nil),                // 17: sso.UserIDRequest
	(*BatchGetUsersRequest)(nil),         // 18: sso.BatchGetUsersRequest
	(*UserData)(nil),                     // 19: sso.UserData
	(*BatchGetUsersResponse)(nil),        // 20: sso.BatchGetUsersResponse
	(*ListUsersRequest)(nil),             // 21: sso.ListUsersRequest
	(*ListUsersResponse)(nil),            // 22: sso.ListUsersResponse
	(*CreateUserRequest)(nil),            // 23: sso.CreateUserRequest
	(*UpdateUserRequest)(nil),            // 24: sso.UpdateUserRequest
}
var file_api_sso_sso_proto_depIdxs = []int32{
	7,  // 0: sso.GetAuthConfigResponse.oidc_providers:type_name -> sso.OIDCProviderData
	19, // 1: sso.CheckPermissionResponse.user:type_name -> sso.UserData
	19, // 2: sso.BatchGetUsersResponse.users:type_name -> sso.UserData
	19, // 3: sso.ListUsersResponse.users:type_name -> sso.UserData
	0,  // 4: sso.Auth.Register:input_type -> sso.RegisterRequest
	2,  // 5: sso.Auth.Login:input_type -> sso.LoginRequest
	4,  // 6: sso.Auth.Refresh:input_type -> sso.RefreshRequest
	6,  // 7: sso.Auth.GetAuthConfig:input_type -> sso.GetAuthConfigRequest
	9,  // 8: sso.Auth.StartOIDCLogin:input_type -> sso.StartOIDCLoginRequest
	11, // 9: sso.Auth.CompleteOIDCCallback:input_type -> sso.CompleteOIDCCallbackRequest
	13, // 10: sso.UserAPI.VerifyAccessToken:input_type -> sso.VerifyTokenRequest
	14, // 11: sso.UserAPI.CheckPermission:input_type -> sso.CheckPermissionRequest
	16, // 12: sso.UserAPI.GetUser:input_type -> sso.GetUserRequest
	18, // 13: sso.UserAPI.BatchGetUsers:input_type -> sso.BatchGetUsersRequest
	21, // 14: sso.UserAPI.ListUsers:input_type -> sso.ListUsersRequest
	23, // 15: sso.UserAPI.CreateUser:input_type -> sso.CreateUserRequest
	24, // 16: sso.UserAPI.UpdateUser:input_type -> sso.UpdateUserRequest
	17, // 17: sso.UserAPI.DeactivateUser:input_type -> sso.UserIDRequest
	17, // 18: sso.UserAPI.ReactivateUser:input_type -> sso.UserIDRequest
	1,  // 19: sso.Auth.Register:output_type -> sso.RegisterResponse
	3,  // 20: sso.Auth.Login:output_type -> sso.LoginResponse
	5,  // 21: sso.Auth.Refresh:output_type -> sso.RefreshResponse
	8,  // 22: sso.Auth.GetAuthConfig:output_type -> sso.GetAuthConfigResponse
	10, // 23: sso.Auth.StartOIDCLogin:output_type -> sso.StartOIDCLoginResponse
	12, // 24: sso.Auth.CompleteOIDCCallback:output_type -> sso.CompleteOIDCCallbackResponse
	19, // 25: sso.UserAPI.VerifyAccessToken:output_type -> sso.UserData
	15, // 26: sso.UserAPI.CheckPermission:output_type -> sso.CheckPermissionResponse
	19, // 27: sso.UserAPI.GetUser:output_type -> sso.UserData
	20, // 28: sso.UserAPI.BatchGetUsers:output_type -> sso.BatchGetUsersResponse
	22, // 29: sso.UserAPI.ListUsers:output_type -> sso.ListUsersResponse
	19, // 30: sso.UserAPI.CreateUser:output_type -> sso.UserData
	19, // 31: sso.UserAPI.UpdateUser:output_type -> sso.UserData
	19, // 32: sso.UserAPI.DeactivateUser:output_type -> sso.UserData
	19, // 33: sso.UserAPI.ReactivateUser:output_type -> sso.UserData
	19, // [19:34] is the sub-list for method output_type
	4,  // [4:19] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_sso_sso_proto_init() }
func file_api_sso_sso_proto_init() {
	if File_api_sso_sso_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sso_sso_proto_rawDesc), len(file_api_sso_sso_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_sso_sso_proto_goTypes,
		DependencyIndexes: file_api_sso_sso_proto_depIdxs,
		MessageInfos:      file_api_sso_sso_proto_msgTypes,
	}.Build()
	File_api_sso_sso_proto = out.File
	file_api_sso_sso_proto_goTypes = nil
	file_api_sso_sso_proto_depIdxs = nil
}
