package model

type SystemConfig struct {
	BaseDomain                           string
	DefaultMemoryReservationBytes        int64
	ReservedSystemMemoryBytes            int64
	OvercommitFactor                     float64
	MaxBurstMultiplier                   int64
	DefaultCpuShares                     int64
	HighLoadCpuShares                    int64
	HighLoadContainerCount               int
	ContainerStopTimeout                 int
	MaxLogSize                           string
	MaxLogFiles                          string
	ContainerDiskQuota                   string
	ReservedDomainPrefixes               []string
	MaxVolumesPerUser                    int
	MaxContainersPerUser                 int
	RegistryApiUrl                       string
	RegistryPublicUrl                    string
	ContainerTtlHours                    int64
	ContainerPidsLimit                   int64
	ContainerMemorySwapMultiplier        float64
	ProxyNetworkName                     string
	RegistryContainerName                string
	ImageBuildsEnabled                   bool
	BuildMemoryBytes                     int64
	BuildCpuQuota                        int64
	BuildCpuPeriod                       int64
	BuildMemorySwapMultiplier            float64
	BuildPidsLimit                       int64
	BuildNetworkName                     string
	KanikoImage                          string
	MaxBuildTimeMinutes                  int64
	MaxConcurrentBuilds                  int
	MaxUploadSizeBytes                   int64
	MaxArchiveSizeBytes                  int64
	MaxUnpackedSizeBytes                 int64
	MaxBuildLogSizeBytes                 int64
	BuildCancelPollIntervalSeconds       int64
	TtlWorkerIntervalSeconds             int64
	GcWorkerIntervalMinutes              int64
	StaleBuildTimeoutMinutes             int64
	EventSyncIntervalSeconds             int64
	EventReconnectDelaySeconds           int64
	BuildOutboxIntervalSeconds           int64
	BuildOutboxBatchSize                 int
	ComposeUploadMaxBytes                int64
	ComposePipelineTimeoutMinutes        int64
	ComposeBuildPollIntervalSeconds      int64
	ComposeDependencyWaitTimeoutMinutes  int64
	ComposeDependencyPollIntervalSeconds int64
	TelemetryMaxLogTailLines             int
	TelemetryMaxLogStreamsPerUser        int
	TelemetryMaxTerminalSessionsPerUser  int
	TelemetryTerminalIdleTimeoutSeconds  int64
	TelemetryTerminalMaxDurationSeconds  int64
	TelemetryAllowedExecCommands         []string
	TelemetryMaxCommandArgs              int
	TelemetryMaxCommandArgBytes          int
	TelemetryWSReadLimitBytes            int64
}
