package model

type SystemConfig struct {
	BaseDomain                           string
	DefaultMemoryReservationBytes        int64
	ReservedSystemMemoryBytes            int64
	OvercommitFactor                     float64
	MaxBurstMultiplier                   int64
	DefaultCPUReservationMillicores      int64
	ReservedSystemCPUMillicores          int64
	CPUOvercommitFactor                  float64
	MaxCPUBurstMultiplier                int64
	ContainerCPUPeriod                   int64
	DefaultCpuShares                     int64
	HighLoadCpuShares                    int64
	HighLoadContainerCount               int
	ContainerStopTimeout                 int
	MaxLogSize                           string
	MaxLogFiles                          string
	ContainerDiskQuota                   string
	ReservedDomainPrefixes               []string
	BlockedDomainPrefixPatterns          []string
	MaxVolumesPerUser                    int
	MaxContainersPerUser                 int
	ContainerTtlHours                    int64
	ContainerPidsLimit                   int64
	ContainerMemorySwapMultiplier        float64
	ImageBuildsEnabled                   bool
	BuildMemoryBytes                     int64
	BuildCpuQuota                        int64
	BuildCpuPeriod                       int64
	BuildMemorySwapMultiplier            float64
	BuildPidsLimit                       int64
	KanikoImage                          string
	MaxBuildTimeMinutes                  int64
	MaxConcurrentBuilds                  int
	MaxUploadSizeBytes                   int64
	MaxArchiveSizeBytes                  int64
	MaxUnpackedSizeBytes                 int64
	MaxBuildLogSizeBytes                 int64
	BuildCancelPollIntervalSeconds       int64
	TtlWorkerIntervalSeconds             int64
	GcWorkerIntervalMinutes              int64
	StaleBuildTimeoutMinutes             int64
	EventSyncIntervalSeconds             int64
	EventReconnectDelaySeconds           int64
	BuildOutboxIntervalSeconds           int64
	BuildOutboxBatchSize                 int
	ReportsUsageSnapshotIntervalSeconds  int64
	ContainerCreateWorkerCount           int
	ContainerCreateMaxAttempts           int
	ContainerCreateTimeoutMinutes        int64
	MaxQueuedContainerCreatesPerUser     int
	ContainerCreateOutboxIntervalSeconds int64
	ContainerCreateOutboxBatchSize       int
	MaxStagedSourceBytesPerUser          int64
	MaxQueuedBuildsPerUser               int
	ComposeUploadMaxBytes                int64
	ComposePipelineTimeoutMinutes        int64
	ComposeDeployWorkerCount             int
	ComposeOutboxIntervalSeconds         int64
	ComposeOutboxBatchSize               int
	ComposeDeployMaxAttempts             int
	MaxQueuedComposeDeploysPerUser       int
	ComposeBuildPollIntervalSeconds      int64
	ComposeDependencyWaitTimeoutMinutes  int64
	ComposeDependencyPollIntervalSeconds int64
	ComposeCoordinatorIntervalSeconds    int64
	HostMinFreeDiskBytes                 int64
	GitSourcesEnabled                    bool
	GitAllowedHosts                      []string
	GitCloneTimeoutSeconds               int64
	GitMaxRepositoryBytes                int64
	TelemetryMaxLogTailLines             int
	TelemetryMaxLogStreamsPerUser        int
	TelemetryMaxTerminalSessionsPerUser  int
	TelemetryTerminalIdleTimeoutSeconds  int64
	TelemetryTerminalMaxDurationSeconds  int64
	TelemetryAllowedExecCommands         []string
	TelemetryMaxCommandArgs              int
	TelemetryMaxCommandArgBytes          int
	TelemetryWSReadLimitBytes            int64
}
