// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	IsReadonly    bool                   `protobuf:"varint,3,opt,name=is_readonly,json=isReadonly,proto3" json:"is_readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeMount) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *VolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *VolumeMount) GetIsReadonly() bool {
	if x != nil {
		return x.IsReadonly
	}
	return false
}

type CreateContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageTag      string                 `protobuf:"bytes,3,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	InternalPort  int32                  `protobuf:"varint,4,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,5,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	VolumeMounts  []*VolumeMount         `protobuf:"bytes,6,rep,name=volume_mounts,json=volumeMounts,proto3" json:"volume_mounts,omitempty"`
	DomainPrefix  string                 `protobuf:"bytes,7,opt,name=domain_prefix,json=domainPrefix,proto3" json:"domain_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *CreateContainerRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateContainerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateContainerRequest) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *CreateContainerRequest) GetInternalPort() int32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *CreateContainerRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *CreateContainerRequest) GetVolumeMounts() []*VolumeMount {
	if x != nil {
		return x.VolumeMounts
	}
	return nil
}

func (x *CreateContainerRequest) GetDomainPrefix() string {
	if x != nil {
		return x.DomainPrefix
	}
	return ""
}

type CreateContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *CreateContainerResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type ContainerActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerActionRequest) Reset() {
	*x = ContainerActionRequest{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerActionRequest) ProtoMessage() {}

func (x *ContainerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerActionRequest.ProtoReflect.Descriptor instead.
func (*ContainerActionRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerActionRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ContainerActionRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ExposeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	DomainPrefix  string                 `protobuf:"bytes,3,opt,name=domain_prefix,json=domainPrefix,proto3" json:"domain_prefix,omitempty"`
	InternalPort  int32                  `protobuf:"varint,4,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExposeRequest) Reset() {
	*x = ExposeRequest{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposeRequest) ProtoMessage() {}

func (x *ExposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposeRequest.ProtoReflect.Descriptor instead.
func (*ExposeRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *ExposeRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ExposeRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ExposeRequest) GetDomainPrefix() string {
	if x != nil {
		return x.DomainPrefix
	}
	return ""
}

func (x *ExposeRequest) GetInternalPort() int32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

type ContainerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DockerId      string                 `protobuf:"bytes,2,opt,name=docker_id,json=dockerId,proto3" json:"docker_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ImageTag      string                 `protobuf:"bytes,4,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	InternalPort  int32                  `protobuf:"varint,5,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	DomainPrefix  string                 `protobuf:"bytes,6,opt,name=domain_prefix,json=domainPrefix,proto3" json:"domain_prefix,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerData) Reset() {
	*x = ContainerData{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerData) ProtoMessage() {}

func (x *ContainerData) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerData.ProtoReflect.Descriptor instead.
func (*ContainerData) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerData) GetDockerId() string {
	if x != nil {
		return x.DockerId
	}
	return ""
}

func (x *ContainerData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerData) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *ContainerData) GetInternalPort() int32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *ContainerData) GetDomainPrefix() string {
	if x != nil {
		return x.DomainPrefix
	}
	return ""
}

func (x *ContainerData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ContainerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerData       `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerListResponse) Reset() {
	*x = ContainerListResponse{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerListResponse) ProtoMessage() {}

func (x *ContainerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerListResponse.ProtoReflect.Descriptor instead.
func (*ContainerListResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerListResponse) GetContainers() []*ContainerData {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ImageActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageActionRequest) Reset() {
	*x = ImageActionRequest{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageActionRequest) ProtoMessage() {}

func (x *ImageActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageActionRequest.ProtoReflect.Descriptor instead.
func (*ImageActionRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *ImageActionRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ImageActionRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type InitBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	LogFilePath   string                 `protobuf:"bytes,3,opt,name=log_file_path,json=logFilePath,proto3" json:"log_file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitBuildRequest) Reset() {
	*x = InitBuildRequest{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBuildRequest) ProtoMessage() {}

func (x *InitBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBuildRequest.ProtoReflect.Descriptor instead.
func (*InitBuildRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10}
}

func (x *InitBuildRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *InitBuildRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InitBuildRequest) GetLogFilePath() string {
	if x != nil {
		return x.LogFilePath
	}
	return ""
}

type InitBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitBuildResponse) Reset() {
	*x = InitBuildResponse{}
	mi := &file_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBuildResponse) ProtoMessage() {}

func (x *InitBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBuildResponse.ProtoReflect.Descriptor instead.
func (*InitBuildResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{11}
}

func (x *InitBuildResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *InitBuildResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type CompleteBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	SizeMb        int32                  `protobuf:"varint,4,opt,name=size_mb,json=sizeMb,proto3" json:"size_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteBuildRequest) Reset() {
	*x = CompleteBuildRequest{}
	mi := &file_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBuildRequest) ProtoMessage() {}

func (x *CompleteBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBuildRequest.ProtoReflect.Descriptor instead.
func (*CompleteBuildRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *CompleteBuildRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *CompleteBuildRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CompleteBuildRequest) GetSizeMb() int32 {
	if x != nil {
		return x.SizeMb
	}
	return 0
}

type ImageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	SizeMb        int32                  `protobuf:"varint,3,opt,name=size_mb,json=sizeMb,proto3" json:"size_mb,omitempty"`
	IsCustom      bool                   `protobuf:"varint,4,opt,name=is_custom,json=isCustom,proto3" json:"is_custom,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageData) Reset() {
	*x = ImageData{}
	mi := &file_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageData) ProtoMessage() {}

func (x *ImageData) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageData.ProtoReflect.Descriptor instead.
func (*ImageData) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{13}
}

func (x *ImageData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageData) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ImageData) GetSizeMb() int32 {
	if x != nil {
		return x.SizeMb
	}
	return 0
}

func (x *ImageData) GetIsCustom() bool {
	if x != nil {
		return x.IsCustom
	}
	return false
}

func (x *ImageData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ImageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ImageData           `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageListResponse) Reset() {
	*x = ImageListResponse{}
	mi := &file_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListResponse) ProtoMessage() {}

func (x *ImageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageListResponse.ProtoReflect.Descriptor instead.
func (*ImageListResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{14}
}

func (x *ImageListResponse) GetImages() []*ImageData {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,3,opt,name=driver,proto3" json:"driver,omitempty"`
	DriverOpts    map[string]string      `protobuf:"bytes,4,rep,name=driver_opts,json=driverOpts,proto3" json:"driver_opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{15}
}

func (x *CreateVolumeRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVolumeRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *CreateVolumeRequest) GetDriverOpts() map[string]string {
	if x != nil {
		return x.DriverOpts
	}
	return nil
}

type CreateVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeResponse) Reset() {
	*x = CreateVolumeResponse{}
	mi := &file_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeResponse) ProtoMessage() {}

func (x *CreateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{16}
}

func (x *CreateVolumeResponse) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type VolumeActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	VolumeId      string                 `protobuf:"bytes,2,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeActionRequest) Reset() {
	*x = VolumeActionRequest{}
	mi := &file_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeActionRequest) ProtoMessage() {}

func (x *VolumeActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeActionRequest.ProtoReflect.Descriptor instead.
func (*VolumeActionRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{17}
}

func (x *VolumeActionRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *VolumeActionRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type VolumeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DockerName    string                 `protobuf:"bytes,2,opt,name=docker_name,json=dockerName,proto3" json:"docker_name,omitempty"`
	Driver        string                 `protobuf:"bytes,3,opt,name=driver,proto3" json:"driver,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeData) Reset() {
	*x = VolumeData{}
	mi := &file_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeData) ProtoMessage() {}

func (x *VolumeData) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeData.ProtoReflect.Descriptor instead.
func (*VolumeData) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{18}
}

func (x *VolumeData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VolumeData) GetDockerName() string {
	if x != nil {
		return x.DockerName
	}
	return ""
}

func (x *VolumeData) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *VolumeData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type VolumeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*VolumeData          `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeListResponse) Reset() {
	*x = VolumeListResponse{}
	mi := &file_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeListResponse) ProtoMessage() {}

func (x *VolumeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeListResponse.ProtoReflect.Descriptor instead.
func (*VolumeListResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{19}
}

func (x *VolumeListResponse) GetVolumes() []*VolumeData {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type BuildActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildActionRequest) Reset() {
	*x = BuildActionRequest{}
	mi := &file_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildActionRequest) ProtoMessage() {}

func (x *BuildActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildActionRequest.ProtoReflect.Descriptor instead.
func (*BuildActionRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{20}
}

func (x *BuildActionRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *BuildActionRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type BuildData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	LogFilePath   string                 `protobuf:"bytes,6,opt,name=log_file_path,json=logFilePath,proto3" json:"log_file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildData) Reset() {
	*x = BuildData{}
	mi := &file_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildData) ProtoMessage() {}

func (x *BuildData) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildData.ProtoReflect.Descriptor instead.
func (*BuildData) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{21}
}

func (x *BuildData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuildData) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *BuildData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BuildData) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *BuildData) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *BuildData) GetLogFilePath() string {
	if x != nil {
		return x.LogFilePath
	}
	return ""
}

type BuildListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builds        []*BuildData           `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildListResponse) Reset() {
	*x = BuildListResponse{}
	mi := &file_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildListResponse) ProtoMessage() {}

func (x *BuildListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildListResponse.ProtoReflect.Descriptor instead.
func (*BuildListResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{22}
}

func (x *BuildListResponse) GetBuilds() []*BuildData {
	if x != nil {
		return x.Builds
	}
	return nil
}

type ProjectData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectData) Reset() {
	*x = ProjectData{}
	mi := &file_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectData) ProtoMessage() {}

func (x *ProjectData) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectData.ProtoReflect.Descriptor instead.
func (*ProjectData) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{23}
}

func (x *ProjectData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProjectData) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProjectData) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ProjectListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*ProjectData         `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectListResponse) Reset() {
	*x = ProjectListResponse{}
	mi := &file_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectListResponse) ProtoMessage() {}

func (x *ProjectListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectListResponse.ProtoReflect.Descriptor instead.
func (*ProjectListResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{24}
}

func (x *ProjectListResponse) GetProjects() []*ProjectData {
	if x != nil {
		return x.Projects
	}
	return nil
}

type ProjectActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectActionRequest) Reset() {
	*x = ProjectActionRequest{}
	mi := &file_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectActionRequest) ProtoMessage() {}

func (x *ProjectActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectActionRequest.ProtoReflect.Descriptor instead.
func (*ProjectActionRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{25}
}

func (x *ProjectActionRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ProjectActionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{26}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PaginatedContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerData       `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedContainerResponse) Reset() {
	*x = PaginatedContainerResponse{}
	mi := &file_core_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedContainerResponse) ProtoMessage() {}

func (x *PaginatedContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedContainerResponse.ProtoReflect.Descriptor instead.
func (*PaginatedContainerResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{27}
}

func (x *PaginatedContainerResponse) GetContainers() []*ContainerData {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *PaginatedContainerResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type PaginatedVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*VolumeData          `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedVolumeResponse) Reset() {
	*x = PaginatedVolumeResponse{}
	mi := &file_core_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedVolumeResponse) ProtoMessage() {}

func (x *PaginatedVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedVolumeResponse.ProtoReflect.Descriptor instead.
func (*PaginatedVolumeResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{28}
}

func (x *PaginatedVolumeResponse) GetVolumes() []*VolumeData {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *PaginatedVolumeResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type PaginatedImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ImageData           `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedImageResponse) Reset() {
	*x = PaginatedImageResponse{}
	mi := &file_core_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedImageResponse) ProtoMessage() {}

func (x *PaginatedImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedImageResponse.ProtoReflect.Descriptor instead.
func (*PaginatedImageResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{29}
}

func (x *PaginatedImageResponse) GetImages() []*ImageData {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *PaginatedImageResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type PaginatedBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builds        []*BuildData           `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedBuildResponse) Reset() {
	*x = PaginatedBuildResponse{}
	mi := &file_core_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedBuildResponse) ProtoMessage() {}

func (x *PaginatedBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedBuildResponse.ProtoReflect.Descriptor instead.
func (*PaginatedBuildResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{30}
}

func (x *PaginatedBuildResponse) GetBuilds() []*BuildData {
	if x != nil {
		return x.Builds
	}
	return nil
}

func (x *PaginatedBuildResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type PaginatedProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*ProjectData         `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedProjectResponse) Reset() {
	*x = PaginatedProjectResponse{}
	mi := &file_core_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedProjectResponse) ProtoMessage() {}

func (x *PaginatedProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedProjectResponse.ProtoReflect.Descriptor instead.
func (*PaginatedProjectResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{31}
}

func (x *PaginatedProjectResponse) GetProjects() []*ProjectData {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *PaginatedProjectResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type SystemConfigData struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	BaseDomain                    string                 `protobuf:"bytes,1,opt,name=base_domain,json=baseDomain,proto3" json:"base_domain,omitempty"`
	DefaultMemoryReservationBytes int64                  `protobuf:"varint,2,opt,name=default_memory_reservation_bytes,json=defaultMemoryReservationBytes,proto3" json:"default_memory_reservation_bytes,omitempty"`
	ReservedSystemMemoryBytes     int64                  `protobuf:"varint,3,opt,name=reserved_system_memory_bytes,json=reservedSystemMemoryBytes,proto3" json:"reserved_system_memory_bytes,omitempty"`
	OvercommitFactor              float64                `protobuf:"fixed64,4,opt,name=overcommit_factor,json=overcommitFactor,proto3" json:"overcommit_factor,omitempty"`
	MaxBurstMultiplier            int64                  `protobuf:"varint,5,opt,name=max_burst_multiplier,json=maxBurstMultiplier,proto3" json:"max_burst_multiplier,omitempty"`
	DefaultCpuShares              int64                  `protobuf:"varint,6,opt,name=default_cpu_shares,json=defaultCpuShares,proto3" json:"default_cpu_shares,omitempty"`
	HighLoadCpuShares             int64                  `protobuf:"varint,7,opt,name=high_load_cpu_shares,json=highLoadCpuShares,proto3" json:"high_load_cpu_shares,omitempty"`
	HighLoadContainerCount        int32                  `protobuf:"varint,8,opt,name=high_load_container_count,json=highLoadContainerCount,proto3" json:"high_load_container_count,omitempty"`
	ContainerStopTimeout          int32                  `protobuf:"varint,9,opt,name=container_stop_timeout,json=containerStopTimeout,proto3" json:"container_stop_timeout,omitempty"`
	MaxLogSize                    string                 `protobuf:"bytes,10,opt,name=max_log_size,json=maxLogSize,proto3" json:"max_log_size,omitempty"`
	MaxLogFiles                   string                 `protobuf:"bytes,11,opt,name=max_log_files,json=maxLogFiles,proto3" json:"max_log_files,omitempty"`
	ContainerDiskQuota            string                 `protobuf:"bytes,12,opt,name=container_disk_quota,json=containerDiskQuota,proto3" json:"container_disk_quota,omitempty"`
	MaxVolumesPerUser             int32                  `protobuf:"varint,13,opt,name=max_volumes_per_user,json=maxVolumesPerUser,proto3" json:"max_volumes_per_user,omitempty"`
	MaxContainersPerUser          int32                  `protobuf:"varint,14,opt,name=max_containers_per_user,json=maxContainersPerUser,proto3" json:"max_containers_per_user,omitempty"`
	RegistryUrl                   string                 `protobuf:"bytes,15,opt,name=registry_url,json=registryUrl,proto3" json:"registry_url,omitempty"`
	ContainerTtlHours             int64                  `protobuf:"varint,16,opt,name=container_ttl_hours,json=containerTtlHours,proto3" json:"container_ttl_hours,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SystemConfigData) Reset() {
	*x = SystemConfigData{}
	mi := &file_core_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemConfigData) ProtoMessage() {}

func (x *SystemConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemConfigData.ProtoReflect.Descriptor instead.
func (*SystemConfigData) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{32}
}

func (x *SystemConfigData) GetBaseDomain() string {
	if x != nil {
		return x.BaseDomain
	}
	return ""
}

func (x *SystemConfigData) GetDefaultMemoryReservationBytes() int64 {
	if x != nil {
		return x.DefaultMemoryReservationBytes
	}
	return 0
}

func (x *SystemConfigData) GetReservedSystemMemoryBytes() int64 {
	if x != nil {
		return x.ReservedSystemMemoryBytes
	}
	return 0
}

func (x *SystemConfigData) GetOvercommitFactor() float64 {
	if x != nil {
		return x.OvercommitFactor
	}
	return 0
}

func (x *SystemConfigData) GetMaxBurstMultiplier() int64 {
	if x != nil {
		return x.MaxBurstMultiplier
	}
	return 0
}

func (x *SystemConfigData) GetDefaultCpuShares() int64 {
	if x != nil {
		return x.DefaultCpuShares
	}
	return 0
}

func (x *SystemConfigData) GetHighLoadCpuShares() int64 {
	if x != nil {
		return x.HighLoadCpuShares
	}
	return 0
}

func (x *SystemConfigData) GetHighLoadContainerCount() int32 {
	if x != nil {
		return x.HighLoadContainerCount
	}
	return 0
}

func (x *SystemConfigData) GetContainerStopTimeout() int32 {
	if x != nil {
		return x.ContainerStopTimeout
	}
	return 0
}

func (x *SystemConfigData) GetMaxLogSize() string {
	if x != nil {
		return x.MaxLogSize
	}
	return ""
}

func (x *SystemConfigData) GetMaxLogFiles() string {
	if x != nil {
		return x.MaxLogFiles
	}
	return ""
}

func (x *SystemConfigData) GetContainerDiskQuota() string {
	if x != nil {
		return x.ContainerDiskQuota
	}
	return ""
}

func (x *SystemConfigData) GetMaxVolumesPerUser() int32 {
	if x != nil {
		return x.MaxVolumesPerUser
	}
	return 0
}

func (x *SystemConfigData) GetMaxContainersPerUser() int32 {
	if x != nil {
		return x.MaxContainersPerUser
	}
	return 0
}

func (x *SystemConfigData) GetRegistryUrl() string {
	if x != nil {
		return x.RegistryUrl
	}
	return ""
}

func (x *SystemConfigData) GetContainerTtlHours() int64 {
	if x != nil {
		return x.ContainerTtlHours
	}
	return 0
}

type ContainerStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuPercentage    float64                `protobuf:"fixed64,1,opt,name=cpu_percentage,json=cpuPercentage,proto3" json:"cpu_percentage,omitempty"`
	MemoryUsageBytes int64                  `protobuf:"varint,2,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	MemoryLimitBytes int64                  `protobuf:"varint,3,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	NetworkRxBytes   int64                  `protobuf:"varint,4,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes   int64                  `protobuf:"varint,5,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContainerStatsResponse) Reset() {
	*x = ContainerStatsResponse{}
	mi := &file_core_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatsResponse) ProtoMessage() {}

func (x *ContainerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatsResponse.ProtoReflect.Descriptor instead.
func (*ContainerStatsResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{33}
}

func (x *ContainerStatsResponse) GetCpuPercentage() float64 {
	if x != nil {
		return x.CpuPercentage
	}
	return 0
}

func (x *ContainerStatsResponse) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *ContainerStatsResponse) GetMemoryLimitBytes() int64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ContainerStatsResponse) GetNetworkRxBytes() int64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *ContainerStatsResponse) GetNetworkTxBytes() int64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x04core\"\a\n" +
	"\x05Empty\"+\n" +
	"\x0eGetUserRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"j\n" +
	"\vVolumeMount\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x1f\n" +
	"\vis_readonly\x18\x03 \x01(\bR\n" +
	"isReadonly\"\xe8\x02\n" +
	"\x16CreateContainerRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_tag\x18\x03 \x01(\tR\bimageTag\x12#\n" +
	"\rinternal_port\x18\x04 \x01(\x05R\finternalPort\x12D\n" +
	"\benv_vars\x18\x05 \x03(\v2).core.CreateContainerRequest.EnvVarsEntryR\aenvVars\x126\n" +
	"\rvolume_mounts\x18\x06 \x03(\v2\x11.core.VolumeMountR\fvolumeMounts\x12#\n" +
	"\rdomain_prefix\x18\a \x01(\tR\fdomainPrefix\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x17CreateContainerResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"n\n" +
	"\x16ContainerActionRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\x97\x01\n" +
	"\rExposeRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12#\n" +
	"\rdomain_prefix\x18\x03 \x01(\tR\fdomainPrefix\x12#\n" +
	"\rinternal_port\x18\x04 \x01(\x05R\finternalPort\"\xee\x01\n" +
	"\rContainerData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdocker_id\x18\x02 \x01(\tR\bdockerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_tag\x18\x04 \x01(\tR\bimageTag\x12#\n" +
	"\rinternal_port\x18\x05 \x01(\x05R\finternalPort\x12#\n" +
	"\rdomain_prefix\x18\x06 \x01(\tR\fdomainPrefix\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"L\n" +
	"\x15ContainerListResponse\x123\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x13.core.ContainerDataR\n" +
	"containers\"J\n" +
	"\x12ImageActionRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\"c\n" +
	"\x10InitBuildRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\"\n" +
	"\rlog_file_path\x18\x03 \x01(\tR\vlogFilePath\"I\n" +
	"\x11InitBuildResponse\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\"}\n" +
	"\x14CompleteBuildRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x17\n" +
	"\asize_mb\x18\x04 \x01(\x05R\x06sizeMb\"\x82\x01\n" +
	"\tImageData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x17\n" +
	"\asize_mb\x18\x03 \x01(\x05R\x06sizeMb\x12\x1b\n" +
	"\tis_custom\x18\x04 \x01(\bR\bisCustom\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"<\n" +
	"\x11ImageListResponse\x12'\n" +
	"\x06images\x18\x01 \x03(\v2\x0f.core.ImageDataR\x06images\"\xe7\x01\n" +
	"\x13CreateVolumeRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x03 \x01(\tR\x06driver\x12J\n" +
	"\vdriver_opts\x18\x04 \x03(\v2).core.CreateVolumeRequest.DriverOptsEntryR\n" +
	"driverOpts\x1a=\n" +
	"\x0fDriverOptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x14CreateVolumeResponse\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"M\n" +
	"\x13VolumeActionRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1b\n" +
	"\tvolume_id\x18\x02 \x01(\tR\bvolumeId\"t\n" +
	"\n" +
	"VolumeData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocker_name\x18\x02 \x01(\tR\n" +
	"dockerName\x12\x16\n" +
	"\x06driver\x18\x03 \x01(\tR\x06driver\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"@\n" +
	"\x12VolumeListResponse\x12*\n" +
	"\avolumes\x18\x01 \x03(\v2\x10.core.VolumeDataR\avolumes\"J\n" +
	"\x12BuildActionRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\"\xb2\x01\n" +
	"\tBuildData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x05 \x01(\x03R\n" +
	"finishedAt\x12\"\n" +
	"\rlog_file_path\x18\x06 \x01(\tR\vlogFilePath\"<\n" +
	"\x11BuildListResponse\x12'\n" +
	"\x06builds\x18\x01 \x03(\v2\x0f.core.BuildDataR\x06builds\"\x8d\x01\n" +
	"\vProjectData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"D\n" +
	"\x13ProjectListResponse\x12-\n" +
	"\bprojects\x18\x01 \x03(\v2\x11.core.ProjectDataR\bprojects\"P\n" +
	"\x14ProjectActionRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"=\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"r\n" +
	"\x1aPaginatedContainerResponse\x123\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x13.core.ContainerDataR\n" +
	"containers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"f\n" +
	"\x17PaginatedVolumeResponse\x12*\n" +
	"\avolumes\x18\x01 \x03(\v2\x10.core.VolumeDataR\avolumes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"b\n" +
	"\x16PaginatedImageResponse\x12'\n" +
	"\x06images\x18\x01 \x03(\v2\x0f.core.ImageDataR\x06images\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"b\n" +
	"\x16PaginatedBuildResponse\x12'\n" +
	"\x06builds\x18\x01 \x03(\v2\x0f.core.BuildDataR\x06builds\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"j\n" +
	"\x18PaginatedProjectResponse\x12-\n" +
	"\bprojects\x18\x01 \x03(\v2\x11.core.ProjectDataR\bprojects\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x9f\x06\n" +
	"\x10SystemConfigData\x12\x1f\n" +
	"\vbase_domain\x18\x01 \x01(\tR\n" +
	"baseDomain\x12G\n" +
	" default_memory_reservation_bytes\x18\x02 \x01(\x03R\x1ddefaultMemoryReservationBytes\x12?\n" +
	"\x1creserved_system_memory_bytes\x18\x03 \x01(\x03R\x19reservedSystemMemoryBytes\x12+\n" +
	"\x11overcommit_factor\x18\x04 \x01(\x01R\x10overcommitFactor\x120\n" +
	"\x14max_burst_multiplier\x18\x05 \x01(\x03R\x12maxBurstMultiplier\x12,\n" +
	"\x12default_cpu_shares\x18\x06 \x01(\x03R\x10defaultCpuShares\x12/\n" +
	"\x14high_load_cpu_shares\x18\a \x01(\x03R\x11highLoadCpuShares\x129\n" +
	"\x19high_load_container_count\x18\b \x01(\x05R\x16highLoadContainerCount\x124\n" +
	"\x16container_stop_timeout\x18\t \x01(\x05R\x14containerStopTimeout\x12 \n" +
	"\fmax_log_size\x18\n" +
	" \x01(\tR\n" +
	"maxLogSize\x12\"\n" +
	"\rmax_log_files\x18\v \x01(\tR\vmaxLogFiles\x120\n" +
	"\x14container_disk_quota\x18\f \x01(\tR\x12containerDiskQuota\x12/\n" +
	"\x14max_volumes_per_user\x18\r \x01(\x05R\x11maxVolumesPerUser\x125\n" +
	"\x17max_containers_per_user\x18\x0e \x01(\x05R\x14maxContainersPerUser\x12!\n" +
	"\fregistry_url\x18\x0f \x01(\tR\vregistryUrl\x12.\n" +
	"\x13container_ttl_hours\x18\x10 \x01(\x03R\x11containerTtlHours\"\xef\x01\n" +
	"\x16ContainerStatsResponse\x12%\n" +
	"\x0ecpu_percentage\x18\x01 \x01(\x01R\rcpuPercentage\x12,\n" +
	"\x12memory_usage_bytes\x18\x02 \x01(\x03R\x10memoryUsageBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x03 \x01(\x03R\x10memoryLimitBytes\x12(\n" +
	"\x10network_rx_bytes\x18\x04 \x01(\x03R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\x05 \x01(\x03R\x0enetworkTxBytes2\xcb\x05\n" +
	"\fContainerAPI\x12N\n" +
	"\x0fCreateContainer\x12\x1c.core.CreateContainerRequest\x1a\x1d.core.CreateContainerResponse\x12;\n" +
	"\x0eStartContainer\x12\x1c.core.ContainerActionRequest\x1a\v.core.Empty\x12:\n" +
	"\rStopContainer\x12\x1c.core.ContainerActionRequest\x1a\v.core.Empty\x12<\n" +
	"\x0fDeleteContainer\x12\x1c.core.ContainerActionRequest\x1a\v.core.Empty\x12F\n" +
	"\x11GetUserContainers\x12\x14.core.GetUserRequest\x1a\x1b.core.ContainerListResponse\x123\n" +
	"\x0fExposeContainer\x12\x13.core.ExposeRequest\x1a\v.core.Empty\x12M\n" +
	"\x10GetAllContainers\x12\x17.core.PaginationRequest\x1a .core.PaginatedContainerResponse\x12A\n" +
	"\x14AdminActionContainer\x12\x1c.core.ContainerActionRequest\x1a\v.core.Empty\x12O\n" +
	"\x11GetContainerStats\x12\x1c.core.ContainerActionRequest\x1a\x1c.core.ContainerStatsResponse\x12T\n" +
	"\x16AdminGetContainerStats\x12\x1c.core.ContainerActionRequest\x1a\x1c.core.ContainerStatsResponse2\xfe\x04\n" +
	"\bImageAPI\x12>\n" +
	"\rGetUserImages\x12\x14.core.GetUserRequest\x1a\x17.core.ImageListResponse\x124\n" +
	"\vDeleteImage\x12\x18.core.ImageActionRequest\x1a\v.core.Empty\x12B\n" +
	"\x0fInitBuildRecord\x12\x16.core.InitBuildRequest\x1a\x17.core.InitBuildResponse\x12>\n" +
	"\x13CompleteBuildRecord\x12\x1a.core.CompleteBuildRequest\x1a\v.core.Empty\x12>\n" +
	"\rGetUserBuilds\x12\x14.core.GetUserRequest\x1a\x17.core.BuildListResponse\x124\n" +
	"\vDeleteBuild\x12\x18.core.BuildActionRequest\x1a\v.core.Empty\x12E\n" +
	"\fGetAllImages\x12\x17.core.PaginationRequest\x1a\x1c.core.PaginatedImageResponse\x129\n" +
	"\x10AdminDeleteImage\x12\x18.core.ImageActionRequest\x1a\v.core.Empty\x12E\n" +
	"\fGetAllBuilds\x12\x17.core.PaginationRequest\x1a\x1c.core.PaginatedBuildResponse\x129\n" +
	"\x10AdminDeleteBuild\x12\x18.core.BuildActionRequest\x1a\v.core.Empty2\xd2\x02\n" +
	"\tVolumeAPI\x12E\n" +
	"\fCreateVolume\x12\x19.core.CreateVolumeRequest\x1a\x1a.core.CreateVolumeResponse\x126\n" +
	"\fDeleteVolume\x12\x19.core.VolumeActionRequest\x1a\v.core.Empty\x12@\n" +
	"\x0eGetUserVolumes\x12\x14.core.GetUserRequest\x1a\x18.core.VolumeListResponse\x12G\n" +
	"\rGetAllVolumes\x12\x17.core.PaginationRequest\x1a\x1d.core.PaginatedVolumeResponse\x12;\n" +
	"\x11AdminDeleteVolume\x12\x19.core.VolumeActionRequest\x1a\v.core.Empty2\x89\x03\n" +
	"\n" +
	"ProjectAPI\x12B\n" +
	"\x0fGetUserProjects\x12\x14.core.GetUserRequest\x1a\x19.core.ProjectListResponse\x128\n" +
	"\rDeleteProject\x12\x1a.core.ProjectActionRequest\x1a\v.core.Empty\x126\n" +
	"\vStopProject\x12\x1a.core.ProjectActionRequest\x1a\v.core.Empty\x12I\n" +
	"\x0eGetAllProjects\x12\x17.core.PaginationRequest\x1a\x1e.core.PaginatedProjectResponse\x12=\n" +
	"\x12AdminDeleteProject\x12\x1a.core.ProjectActionRequest\x1a\v.core.Empty\x12;\n" +
	"\x10AdminStopProject\x12\x1a.core.ProjectActionRequest\x1a\v.core.Empty2r\n" +
	"\tSystemAPI\x120\n" +
	"\tGetConfig\x12\v.core.Empty\x1a\x16.core.SystemConfigData\x123\n" +
	"\fUpdateConfig\x12\x16.core.SystemConfigData\x1a\v.core.EmptyBGZEgithub.com/callmerussell04/docker-cloud-manager/backend/api/core;coreb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_core_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: core.Empty
	(*GetUserRequest)(nil),             // 1: core.GetUserRequest
	(*VolumeMount)(nil),                // 2: core.VolumeMount
	(*CreateContainerRequest)(nil),     // 3: core.CreateContainerRequest
	(*CreateContainerResponse)(nil),    // 4: core.CreateContainerResponse
	(*ContainerActionRequest)(nil),     // 5: core.ContainerActionRequest
	(*ExposeRequest)(nil),              // 6: core.ExposeRequest
	(*ContainerData)(nil),              // 7: core.ContainerData
	(*ContainerListResponse)(nil),      // 8: core.ContainerListResponse
	(*ImageActionRequest)(nil),         // 9: core.ImageActionRequest
	(*InitBuildRequest)(nil),           // 10: core.InitBuildRequest
	(*InitBuildResponse)(nil),          // 11: core.InitBuildResponse
	(*CompleteBuildRequest)(nil),       // 12: core.CompleteBuildRequest
	(*ImageData)(nil),                  // 13: core.ImageData
	(*ImageListResponse)(nil),          // 14: core.ImageListResponse
	(*CreateVolumeRequest)(nil),        // 15: core.CreateVolumeRequest
	(*CreateVolumeResponse)(nil),       // 16: core.CreateVolumeResponse
	(*VolumeActionRequest)(nil),        // 17: core.VolumeActionRequest
	(*VolumeData)(nil),                 // 18: core.VolumeData
	(*VolumeListResponse)(nil),         // 19: core.VolumeListResponse
	(*BuildActionRequest)(nil),         // 20: core.BuildActionRequest
	(*BuildData)(nil),                  // 21: core.BuildData
	(*BuildListResponse)(nil),          // 22: core.BuildListResponse
	(*ProjectData)(nil),                // 23: core.ProjectData
	(*ProjectListResponse)(nil),        // 24: core.ProjectListResponse
	(*ProjectActionRequest)(nil),       // 25: core.ProjectActionRequest
	(*PaginationRequest)(nil),          // 26: core.PaginationRequest
	(*PaginatedContainerResponse)(nil), // 27: core.PaginatedContainerResponse
	(*PaginatedVolumeResponse)(nil),    // 28: core.PaginatedVolumeResponse
	(*PaginatedImageResponse)(nil),     // 29: core.PaginatedImageResponse
	(*PaginatedBuildResponse)(nil),     // 30: core.PaginatedBuildResponse
	(*PaginatedProjectResponse)(nil),   // 31: core.PaginatedProjectResponse
	(*SystemConfigData)(nil),           // 32: core.SystemConfigData
	(*ContainerStatsResponse)(nil),     // 33: core.ContainerStatsResponse
	nil,                                // 34: core.CreateContainerRequest.EnvVarsEntry
	nil,                                // 35: core.CreateVolumeRequest.DriverOptsEntry
}
var file_core_proto_depIdxs = []int32{
	34, // 0: core.CreateContainerRequest.env_vars:type_name -> core.CreateContainerRequest.EnvVarsEntry
	2,  // 1: core.CreateContainerRequest.volume_mounts:type_name -> core.VolumeMount
	7,  // 2: core.ContainerListResponse.containers:type_name -> core.ContainerData
	13, // 3: core.ImageListResponse.images:type_name -> core.ImageData
	35, // 4: core.CreateVolumeRequest.driver_opts:type_name -> core.CreateVolumeRequest.DriverOptsEntry
	18, // 5: core.VolumeListResponse.volumes:type_name -> core.VolumeData
	21, // 6: core.BuildListResponse.builds:type_name -> core.BuildData
	23, // 7: core.ProjectListResponse.projects:type_name -> core.ProjectData
	7,  // 8: core.PaginatedContainerResponse.containers:type_name -> core.ContainerData
	18, // 9: core.PaginatedVolumeResponse.volumes:type_name -> core.VolumeData
	13, // 10: core.PaginatedImageResponse.images:type_name -> core.ImageData
	21, // 11: core.PaginatedBuildResponse.builds:type_name -> core.BuildData
	23, // 12: core.PaginatedProjectResponse.projects:type_name -> core.ProjectData
	3,  // 13: core.ContainerAPI.CreateContainer:input_type -> core.CreateContainerRequest
	5,  // 14: core.ContainerAPI.StartContainer:input_type -> core.ContainerActionRequest
	5,  // 15: core.ContainerAPI.StopContainer:input_type -> core.ContainerActionRequest
	5,  // 16: core.ContainerAPI.DeleteContainer:input_type -> core.ContainerActionRequest
	1,  // 17: core.ContainerAPI.GetUserContainers:input_type -> core.GetUserRequest
	6,  // 18: core.ContainerAPI.ExposeContainer:input_type -> core.ExposeRequest
	26, // 19: core.ContainerAPI.GetAllContainers:input_type -> core.PaginationRequest
	5,  // 20: core.ContainerAPI.AdminActionContainer:input_type -> core.ContainerActionRequest
	5,  // 21: core.ContainerAPI.GetContainerStats:input_type -> core.ContainerActionRequest
	5,  // 22: core.ContainerAPI.AdminGetContainerStats:input_type -> core.ContainerActionRequest
	1,  // 23: core.ImageAPI.GetUserImages:input_type -> core.GetUserRequest
	9,  // 24: core.ImageAPI.DeleteImage:input_type -> core.ImageActionRequest
	10, // 25: core.ImageAPI.InitBuildRecord:input_type -> core.InitBuildRequest
	12, // 26: core.ImageAPI.CompleteBuildRecord:input_type -> core.CompleteBuildRequest
	1,  // 27: core.ImageAPI.GetUserBuilds:input_type -> core.GetUserRequest
	20, // 28: core.ImageAPI.DeleteBuild:input_type -> core.BuildActionRequest
	26, // 29: core.ImageAPI.GetAllImages:input_type -> core.PaginationRequest
	9,  // 30: core.ImageAPI.AdminDeleteImage:input_type -> core.ImageActionRequest
	26, // 31: core.ImageAPI.GetAllBuilds:input_type -> core.PaginationRequest
	20, // 32: core.ImageAPI.AdminDeleteBuild:input_type -> core.BuildActionRequest
	15, // 33: core.VolumeAPI.CreateVolume:input_type -> core.CreateVolumeRequest
	17, // 34: core.VolumeAPI.DeleteVolume:input_type -> core.VolumeActionRequest
	1,  // 35: core.VolumeAPI.GetUserVolumes:input_type -> core.GetUserRequest
	26, // 36: core.VolumeAPI.GetAllVolumes:input_type -> core.PaginationRequest
	17, // 37: core.VolumeAPI.AdminDeleteVolume:input_type -> core.VolumeActionRequest
	1,  // 38: core.ProjectAPI.GetUserProjects:input_type -> core.GetUserRequest
	25, // 39: core.ProjectAPI.DeleteProject:input_type -> core.ProjectActionRequest
	25, // 40: core.ProjectAPI.StopProject:input_type -> core.ProjectActionRequest
	26, // 41: core.ProjectAPI.GetAllProjects:input_type -> core.PaginationRequest
	25, // 42: core.ProjectAPI.AdminDeleteProject:input_type -> core.ProjectActionRequest
	25, // 43: core.ProjectAPI.AdminStopProject:input_type -> core.ProjectActionRequest
	0,  // 44: core.SystemAPI.GetConfig:input_type -> core.Empty
	32, // 45: core.SystemAPI.UpdateConfig:input_type -> core.SystemConfigData
	4,  // 46: core.ContainerAPI.CreateContainer:output_type -> core.CreateContainerResponse
	0,  // 47: core.ContainerAPI.StartContainer:output_type -> core.Empty
	0,  // 48: core.ContainerAPI.StopContainer:output_type -> core.Empty
	0,  // 49: core.ContainerAPI.DeleteContainer:output_type -> core.Empty
	8,  // 50: core.ContainerAPI.GetUserContainers:output_type -> core.ContainerListResponse
	0,  // 51: core.ContainerAPI.ExposeContainer:output_type -> core.Empty
	27, // 52: core.ContainerAPI.GetAllContainers:output_type -> core.PaginatedContainerResponse
	0,  // 53: core.ContainerAPI.AdminActionContainer:output_type -> core.Empty
	33, // 54: core.ContainerAPI.GetContainerStats:output_type -> core.ContainerStatsResponse
	33, // 55: core.ContainerAPI.AdminGetContainerStats:output_type -> core.ContainerStatsResponse
	14, // 56: core.ImageAPI.GetUserImages:output_type -> core.ImageListResponse
	0,  // 57: core.ImageAPI.DeleteImage:output_type -> core.Empty
	11, // 58: core.ImageAPI.InitBuildRecord:output_type -> core.InitBuildResponse
	0,  // 59: core.ImageAPI.CompleteBuildRecord:output_type -> core.Empty
	22, // 60: core.ImageAPI.GetUserBuilds:output_type -> core.BuildListResponse
	0,  // 61: core.ImageAPI.DeleteBuild:output_type -> core.Empty
	29, // 62: core.ImageAPI.GetAllImages:output_type -> core.PaginatedImageResponse
	0,  // 63: core.ImageAPI.AdminDeleteImage:output_type -> core.Empty
	30, // 64: core.ImageAPI.GetAllBuilds:output_type -> core.PaginatedBuildResponse
	0,  // 65: core.ImageAPI.AdminDeleteBuild:output_type -> core.Empty
	16, // 66: core.VolumeAPI.CreateVolume:output_type -> core.CreateVolumeResponse
	0,  // 67: core.VolumeAPI.DeleteVolume:output_type -> core.Empty
	19, // 68: core.VolumeAPI.GetUserVolumes:output_type -> core.VolumeListResponse
	28, // 69: core.VolumeAPI.GetAllVolumes:output_type -> core.PaginatedVolumeResponse
	0,  // 70: core.VolumeAPI.AdminDeleteVolume:output_type -> core.Empty
	24, // 71: core.ProjectAPI.GetUserProjects:output_type -> core.ProjectListResponse
	0,  // 72: core.ProjectAPI.DeleteProject:output_type -> core.Empty
	0,  // 73: core.ProjectAPI.StopProject:output_type -> core.Empty
	31, // 74: core.ProjectAPI.GetAllProjects:output_type -> core.PaginatedProjectResponse
	0,  // 75: core.ProjectAPI.AdminDeleteProject:output_type -> core.Empty
	0,  // 76: core.ProjectAPI.AdminStopProject:output_type -> core.Empty
	32, // 77: core.SystemAPI.GetConfig:output_type -> core.SystemConfigData
	0,  // 78: core.SystemAPI.UpdateConfig:output_type -> core.Empty
	46, // [46:79] is the sub-list for method output_type
	13, // [13:46] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
