// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: api/core/core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContainerAPI_CreateContainer_FullMethodName   = "/core.ContainerAPI/CreateContainer"
	ContainerAPI_StartContainer_FullMethodName    = "/core.ContainerAPI/StartContainer"
	ContainerAPI_StopContainer_FullMethodName     = "/core.ContainerAPI/StopContainer"
	ContainerAPI_DeleteContainer_FullMethodName   = "/core.ContainerAPI/DeleteContainer"
	ContainerAPI_ListContainers_FullMethodName    = "/core.ContainerAPI/ListContainers"
	ContainerAPI_ExposeContainer_FullMethodName   = "/core.ContainerAPI/ExposeContainer"
	ContainerAPI_GetContainerStats_FullMethodName = "/core.ContainerAPI/GetContainerStats"
)

// ContainerAPIClient is the client API for ContainerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContainerAPIClient interface {
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error)
	StartContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error)
	StopContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error)
	ListContainers(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginatedContainerResponse, error)
	ExposeContainer(ctx context.Context, in *ExposeRequest, opts ...grpc.CallOption) (*Empty, error)
	GetContainerStats(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*ContainerStatsResponse, error)
}

type containerAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerAPIClient(cc grpc.ClientConnInterface) ContainerAPIClient {
	return &containerAPIClient{cc}
}

func (c *containerAPIClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContainerResponse)
	err := c.cc.Invoke(ctx, ContainerAPI_CreateContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerAPIClient) StartContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ContainerAPI_StartContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerAPIClient) StopContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ContainerAPI_StopContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerAPIClient) DeleteContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ContainerAPI_DeleteContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerAPIClient) ListContainers(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginatedContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaginatedContainerResponse)
	err := c.cc.Invoke(ctx, ContainerAPI_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerAPIClient) ExposeContainer(ctx context.Context, in *ExposeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ContainerAPI_ExposeContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerAPIClient) GetContainerStats(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*ContainerStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainerStatsResponse)
	err := c.cc.Invoke(ctx, ContainerAPI_GetContainerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerAPIServer is the server API for ContainerAPI service.
// All implementations must embed UnimplementedContainerAPIServer
// for forward compatibility.
type ContainerAPIServer interface {
	CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error)
	StartContainer(context.Context, *ContainerActionRequest) (*Empty, error)
	StopContainer(context.Context, *ContainerActionRequest) (*Empty, error)
	DeleteContainer(context.Context, *ContainerActionRequest) (*Empty, error)
	ListContainers(context.Context, *PaginationRequest) (*PaginatedContainerResponse, error)
	ExposeContainer(context.Context, *ExposeRequest) (*Empty, error)
	GetContainerStats(context.Context, *ContainerActionRequest) (*ContainerStatsResponse, error)
	mustEmbedUnimplementedContainerAPIServer()
}

// UnimplementedContainerAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContainerAPIServer struct{}

func (UnimplementedContainerAPIServer) CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContainer not implemented")
}
func (UnimplementedContainerAPIServer) StartContainer(context.Context, *ContainerActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartContainer not implemented")
}
func (UnimplementedContainerAPIServer) StopContainer(context.Context, *ContainerActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopContainer not implemented")
}
func (UnimplementedContainerAPIServer) DeleteContainer(context.Context, *ContainerActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContainer not implemented")
}
func (UnimplementedContainerAPIServer) ListContainers(context.Context, *PaginationRequest) (*PaginatedContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedContainerAPIServer) ExposeContainer(context.Context, *ExposeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExposeContainer not implemented")
}
func (UnimplementedContainerAPIServer) GetContainerStats(context.Context, *ContainerActionRequest) (*ContainerStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContainerStats not implemented")
}
func (UnimplementedContainerAPIServer) mustEmbedUnimplementedContainerAPIServer() {}
func (UnimplementedContainerAPIServer) testEmbeddedByValue()                      {}

// UnsafeContainerAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerAPIServer will
// result in compilation errors.
type UnsafeContainerAPIServer interface {
	mustEmbedUnimplementedContainerAPIServer()
}

func RegisterContainerAPIServer(s grpc.ServiceRegistrar, srv ContainerAPIServer) {
	// If the following call pancis, it indicates UnimplementedContainerAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContainerAPI_ServiceDesc, srv)
}

func _ContainerAPI_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_CreateContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerAPI_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).StartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_StartContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).StartContainer(ctx, req.(*ContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerAPI_StopContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).StopContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_StopContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).StopContainer(ctx, req.(*ContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerAPI_DeleteContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).DeleteContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_DeleteContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).DeleteContainer(ctx, req.(*ContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerAPI_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).ListContainers(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerAPI_ExposeContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).ExposeContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_ExposeContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).ExposeContainer(ctx, req.(*ExposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerAPI_GetContainerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).GetContainerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_GetContainerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).GetContainerStats(ctx, req.(*ContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContainerAPI_ServiceDesc is the grpc.ServiceDesc for ContainerAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.ContainerAPI",
	HandlerType: (*ContainerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContainer",
			Handler:    _ContainerAPI_CreateContainer_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _ContainerAPI_StartContainer_Handler,
		},
		{
			MethodName: "StopContainer",
			Handler:    _ContainerAPI_StopContainer_Handler,
		},
		{
			MethodName: "DeleteContainer",
			Handler:    _ContainerAPI_DeleteContainer_Handler,
		},
		{
			MethodName: "ListContainers",
			Handler:    _ContainerAPI_ListContainers_Handler,
		},
		{
			MethodName: "ExposeContainer",
			Handler:    _ContainerAPI_ExposeContainer_Handler,
		},
		{
			MethodName: "GetContainerStats",
			Handler:    _ContainerAPI_GetContainerStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/core/core.proto",
}

const (
	ImageAPI_ListImages_FullMethodName          = "/core.ImageAPI/ListImages"
	ImageAPI_DeleteImage_FullMethodName         = "/core.ImageAPI/DeleteImage"
	ImageAPI_InitBuildRecord_FullMethodName     = "/core.ImageAPI/InitBuildRecord"
	ImageAPI_CreateBuildJob_FullMethodName      = "/core.ImageAPI/CreateBuildJob"
	ImageAPI_StartBuildRecord_FullMethodName    = "/core.ImageAPI/StartBuildRecord"
	ImageAPI_CancelBuildRecord_FullMethodName   = "/core.ImageAPI/CancelBuildRecord"
	ImageAPI_CompleteBuildRecord_FullMethodName = "/core.ImageAPI/CompleteBuildRecord"
	ImageAPI_ListBuilds_FullMethodName          = "/core.ImageAPI/ListBuilds"
	ImageAPI_GetBuild_FullMethodName            = "/core.ImageAPI/GetBuild"
	ImageAPI_DeleteBuild_FullMethodName         = "/core.ImageAPI/DeleteBuild"
)

// ImageAPIClient is the client API for ImageAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageAPIClient interface {
	ListImages(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginatedImageResponse, error)
	DeleteImage(ctx context.Context, in *ImageActionRequest, opts ...grpc.CallOption) (*Empty, error)
	InitBuildRecord(ctx context.Context, in *InitBuildRequest, opts ...grpc.CallOption) (*InitBuildResponse, error)
	CreateBuildJob(ctx context.Context, in *CreateBuildJobRequest, opts ...grpc.CallOption) (*InitBuildResponse, error)
	StartBuildRecord(ctx context.Context, in *BuildActionRequest, opts ...grpc.CallOption) (*StartBuildRecordResponse, error)
	CancelBuildRecord(ctx context.Context, in *BuildActionRequest, opts ...grpc.CallOption) (*Empty, error)
	CompleteBuildRecord(ctx context.Context, in *CompleteBuildRequest, opts ...grpc.CallOption) (*Empty, error)
	ListBuilds(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginatedBuildResponse, error)
	GetBuild(ctx context.Context, in *BuildActionRequest, opts ...grpc.CallOption) (*BuildData, error)
	DeleteBuild(ctx context.Context, in *BuildActionRequest, opts ...grpc.CallOption) (*Empty, error)
}

type imageAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewImageAPIClient(cc grpc.ClientConnInterface) ImageAPIClient {
	return &imageAPIClient{cc}
}

func (c *imageAPIClient) ListImages(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginatedImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaginatedImageResponse)
	err := c.cc.Invoke(ctx, ImageAPI_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) DeleteImage(ctx context.Context, in *ImageActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ImageAPI_DeleteImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) InitBuildRecord(ctx context.Context, in *InitBuildRequest, opts ...grpc.CallOption) (*InitBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitBuildResponse)
	err := c.cc.Invoke(ctx, ImageAPI_InitBuildRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) CreateBuildJob(ctx context.Context, in *CreateBuildJobRequest, opts ...grpc.CallOption) (*InitBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitBuildResponse)
	err := c.cc.Invoke(ctx, ImageAPI_CreateBuildJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) StartBuildRecord(ctx context.Context, in *BuildActionRequest, opts ...grpc.CallOption) (*StartBuildRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBuildRecordResponse)
	err := c.cc.Invoke(ctx, ImageAPI_StartBuildRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) CancelBuildRecord(ctx context.Context, in *BuildActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ImageAPI_CancelBuildRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) CompleteBuildRecord(ctx context.Context, in *CompleteBuildRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ImageAPI_CompleteBuildRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) ListBuilds(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginatedBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaginatedBuildResponse)
	err := c.cc.Invoke(ctx, ImageAPI_ListBuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) GetBuild(ctx context.Context, in *BuildActionRequest, opts ...grpc.CallOption) (*BuildData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildData)
	err := c.cc.Invoke(ctx, ImageAPI_GetBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) DeleteBuild(ctx context.Context, in *BuildActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ImageAPI_DeleteBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageAPIServer is the server API for ImageAPI service.
// All implementations must embed UnimplementedImageAPIServer
// for forward compatibility.
type ImageAPIServer interface {
	ListImages(context.Context, *PaginationRequest) (*PaginatedImageResponse, error)
	DeleteImage(context.Context, *ImageActionRequest) (*Empty, error)
	InitBuildRecord(context.Context, *InitBuildRequest) (*InitBuildResponse, error)
	CreateBuildJob(context.Context, *CreateBuildJobRequest) (*InitBuildResponse, error)
	StartBuildRecord(context.Context, *BuildActionRequest) (*StartBuildRecordResponse, error)
	CancelBuildRecord(context.Context, *BuildActionRequest) (*Empty, error)
	CompleteBuildRecord(context.Context, *CompleteBuildRequest) (*Empty, error)
	ListBuilds(context.Context, *PaginationRequest) (*PaginatedBuildResponse, error)
	GetBuild(context.Context, *BuildActionRequest) (*BuildData, error)
	DeleteBuild(context.Context, *BuildActionRequest) (*Empty, error)
	mustEmbedUnimplementedImageAPIServer()
}

// UnimplementedImageAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageAPIServer struct{}

func (UnimplementedImageAPIServer) ListImages(context.Context, *PaginationRequest) (*PaginatedImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedImageAPIServer) DeleteImage(context.Context, *ImageActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteImage not implemented")
}
func (UnimplementedImageAPIServer) InitBuildRecord(context.Context, *InitBuildRequest) (*InitBuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitBuildRecord not implemented")
}
func (UnimplementedImageAPIServer) CreateBuildJob(context.Context, *CreateBuildJobRequest) (*InitBuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBuildJob not implemented")
}
func (UnimplementedImageAPIServer) StartBuildRecord(context.Context, *BuildActionRequest) (*StartBuildRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartBuildRecord not implemented")
}
func (UnimplementedImageAPIServer) CancelBuildRecord(context.Context, *BuildActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBuildRecord not implemented")
}
func (UnimplementedImageAPIServer) CompleteBuildRecord(context.Context, *CompleteBuildRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteBuildRecord not implemented")
}
func (UnimplementedImageAPIServer) ListBuilds(context.Context, *PaginationRequest) (*PaginatedBuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBuilds not implemented")
}
func (UnimplementedImageAPIServer) GetBuild(context.Context, *BuildActionRequest) (*BuildData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuild not implemented")
}
func (UnimplementedImageAPIServer) DeleteBuild(context.Context, *BuildActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBuild not implemented")
}
func (UnimplementedImageAPIServer) mustEmbedUnimplementedImageAPIServer() {}
func (UnimplementedImageAPIServer) testEmbeddedByValue()                  {}

// UnsafeImageAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageAPIServer will
// result in compilation errors.
type UnsafeImageAPIServer interface {
	mustEmbedUnimplementedImageAPIServer()
}

func RegisterImageAPIServer(s grpc.ServiceRegistrar, srv ImageAPIServer) {
	// If the following call pancis, it indicates UnimplementedImageAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageAPI_ServiceDesc, srv)
}

func _ImageAPI_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).ListImages(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_DeleteImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).DeleteImage(ctx, req.(*ImageActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_InitBuildRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).InitBuildRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_InitBuildRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).InitBuildRecord(ctx, req.(*InitBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_CreateBuildJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBuildJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).CreateBuildJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_CreateBuildJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).CreateBuildJob(ctx, req.(*CreateBuildJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_StartBuildRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).StartBuildRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_StartBuildRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).StartBuildRecord(ctx, req.(*BuildActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_CancelBuildRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).CancelBuildRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_CancelBuildRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).CancelBuildRecord(ctx, req.(*BuildActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_CompleteBuildRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).CompleteBuildRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_CompleteBuildRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).CompleteBuildRecord(ctx, req.(*CompleteBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_ListBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).ListBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_ListBuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).ListBuilds(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_GetBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).GetBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_GetBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).GetBuild(ctx, req.(*BuildActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_DeleteBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).DeleteBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_DeleteBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).DeleteBuild(ctx, req.(*BuildActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageAPI_ServiceDesc is the grpc.ServiceDesc for ImageAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.ImageAPI",
	HandlerType: (*ImageAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImages",
			Handler:    _ImageAPI_ListImages_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _ImageAPI_DeleteImage_Handler,
		},
		{
			MethodName: "InitBuildRecord",
			Handler:    _ImageAPI_InitBuildRecord_Handler,
		},
		{
			MethodName: "CreateBuildJob",
			Handler:    _ImageAPI_CreateBuildJob_Handler,
		},
		{
			MethodName: "StartBuildRecord",
			Handler:    _ImageAPI_StartBuildRecord_Handler,
		},
		{
			MethodName: "CancelBuildRecord",
			Handler:    _ImageAPI_CancelBuildRecord_Handler,
		},
		{
			MethodName: "CompleteBuildRecord",
			Handler:    _ImageAPI_CompleteBuildRecord_Handler,
		},
		{
			MethodName: "ListBuilds",
			Handler:    _ImageAPI_ListBuilds_Handler,
		},
		{
			MethodName: "GetBuild",
			Handler:    _ImageAPI_GetBuild_Handler,
		},
		{
			MethodName: "DeleteBuild",
			Handler:    _ImageAPI_DeleteBuild_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/core/core.proto",
}

const (
	VolumeAPI_CreateVolume_FullMethodName = "/core.VolumeAPI/CreateVolume"
	VolumeAPI_DeleteVolume_FullMethodName = "/core.VolumeAPI/DeleteVolume"
	VolumeAPI_ListVolumes_FullMethodName  = "/core.VolumeAPI/ListVolumes"
)

// VolumeAPIClient is the client API for VolumeAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VolumeAPIClient interface {
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	DeleteVolume(ctx context.Context, in *VolumeActionRequest, opts ...grpc.CallOption) (*Empty, error)
	ListVolumes(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginatedVolumeResponse, error)
}

type volumeAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewVolumeAPIClient(cc grpc.ClientConnInterface) VolumeAPIClient {
	return &volumeAPIClient{cc}
}

func (c *volumeAPIClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, VolumeAPI_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeAPIClient) DeleteVolume(ctx context.Context, in *VolumeActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VolumeAPI_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeAPIClient) ListVolumes(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginatedVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaginatedVolumeResponse)
	err := c.cc.Invoke(ctx, VolumeAPI_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumeAPIServer is the server API for VolumeAPI service.
// All implementations must embed UnimplementedVolumeAPIServer
// for forward compatibility.
type VolumeAPIServer interface {
	CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	DeleteVolume(context.Context, *VolumeActionRequest) (*Empty, error)
	ListVolumes(context.Context, *PaginationRequest) (*PaginatedVolumeResponse, error)
	mustEmbedUnimplementedVolumeAPIServer()
}

// UnimplementedVolumeAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolumeAPIServer struct{}

func (UnimplementedVolumeAPIServer) CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedVolumeAPIServer) DeleteVolume(context.Context, *VolumeActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedVolumeAPIServer) ListVolumes(context.Context, *PaginationRequest) (*PaginatedVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedVolumeAPIServer) mustEmbedUnimplementedVolumeAPIServer() {}
func (UnimplementedVolumeAPIServer) testEmbeddedByValue()                   {}

// UnsafeVolumeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolumeAPIServer will
// result in compilation errors.
type UnsafeVolumeAPIServer interface {
	mustEmbedUnimplementedVolumeAPIServer()
}

func RegisterVolumeAPIServer(s grpc.ServiceRegistrar, srv VolumeAPIServer) {
	// If the following call pancis, it indicates UnimplementedVolumeAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolumeAPI_ServiceDesc, srv)
}

func _VolumeAPI_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeAPIServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeAPI_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeAPIServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeAPI_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeAPIServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeAPI_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeAPIServer).DeleteVolume(ctx, req.(*VolumeActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeAPI_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeAPIServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeAPI_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeAPIServer).ListVolumes(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VolumeAPI_ServiceDesc is the grpc.ServiceDesc for VolumeAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolumeAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.VolumeAPI",
	HandlerType: (*VolumeAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVolume",
			Handler:    _VolumeAPI_CreateVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _VolumeAPI_DeleteVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _VolumeAPI_ListVolumes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/core/core.proto",
}

const (
	ProjectAPI_ListProjects_FullMethodName  = "/core.ProjectAPI/ListProjects"
	ProjectAPI_DeleteProject_FullMethodName = "/core.ProjectAPI/DeleteProject"
	ProjectAPI_StartProject_FullMethodName  = "/core.ProjectAPI/StartProject"
	ProjectAPI_StopProject_FullMethodName   = "/core.ProjectAPI/StopProject"
)

// ProjectAPIClient is the client API for ProjectAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectAPIClient interface {
	ListProjects(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginatedProjectResponse, error)
	DeleteProject(ctx context.Context, in *ProjectActionRequest, opts ...grpc.CallOption) (*Empty, error)
	StartProject(ctx context.Context, in *ProjectActionRequest, opts ...grpc.CallOption) (*Empty, error)
	StopProject(ctx context.Context, in *ProjectActionRequest, opts ...grpc.CallOption) (*Empty, error)
}

type projectAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectAPIClient(cc grpc.ClientConnInterface) ProjectAPIClient {
	return &projectAPIClient{cc}
}

func (c *projectAPIClient) ListProjects(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*PaginatedProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaginatedProjectResponse)
	err := c.cc.Invoke(ctx, ProjectAPI_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectAPIClient) DeleteProject(ctx context.Context, in *ProjectActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProjectAPI_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectAPIClient) StartProject(ctx context.Context, in *ProjectActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProjectAPI_StartProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectAPIClient) StopProject(ctx context.Context, in *ProjectActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProjectAPI_StopProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectAPIServer is the server API for ProjectAPI service.
// All implementations must embed UnimplementedProjectAPIServer
// for forward compatibility.
type ProjectAPIServer interface {
	ListProjects(context.Context, *PaginationRequest) (*PaginatedProjectResponse, error)
	DeleteProject(context.Context, *ProjectActionRequest) (*Empty, error)
	StartProject(context.Context, *ProjectActionRequest) (*Empty, error)
	StopProject(context.Context, *ProjectActionRequest) (*Empty, error)
	mustEmbedUnimplementedProjectAPIServer()
}

// UnimplementedProjectAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectAPIServer struct{}

func (UnimplementedProjectAPIServer) ListProjects(context.Context, *PaginationRequest) (*PaginatedProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedProjectAPIServer) DeleteProject(context.Context, *ProjectActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedProjectAPIServer) StartProject(context.Context, *ProjectActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProject not implemented")
}
func (UnimplementedProjectAPIServer) StopProject(context.Context, *ProjectActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProject not implemented")
}
func (UnimplementedProjectAPIServer) mustEmbedUnimplementedProjectAPIServer() {}
func (UnimplementedProjectAPIServer) testEmbeddedByValue()                    {}

// UnsafeProjectAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectAPIServer will
// result in compilation errors.
type UnsafeProjectAPIServer interface {
	mustEmbedUnimplementedProjectAPIServer()
}

func RegisterProjectAPIServer(s grpc.ServiceRegistrar, srv ProjectAPIServer) {
	// If the following call pancis, it indicates UnimplementedProjectAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectAPI_ServiceDesc, srv)
}

func _ProjectAPI_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectAPIServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectAPI_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectAPIServer).ListProjects(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectAPI_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectAPIServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectAPI_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectAPIServer).DeleteProject(ctx, req.(*ProjectActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectAPI_StartProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectAPIServer).StartProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectAPI_StartProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectAPIServer).StartProject(ctx, req.(*ProjectActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectAPI_StopProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectAPIServer).StopProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectAPI_StopProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectAPIServer).StopProject(ctx, req.(*ProjectActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectAPI_ServiceDesc is the grpc.ServiceDesc for ProjectAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.ProjectAPI",
	HandlerType: (*ProjectAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProjects",
			Handler:    _ProjectAPI_ListProjects_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _ProjectAPI_DeleteProject_Handler,
		},
		{
			MethodName: "StartProject",
			Handler:    _ProjectAPI_StartProject_Handler,
		},
		{
			MethodName: "StopProject",
			Handler:    _ProjectAPI_StopProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/core/core.proto",
}

const (
	SystemAPI_GetConfig_FullMethodName    = "/core.SystemAPI/GetConfig"
	SystemAPI_UpdateConfig_FullMethodName = "/core.SystemAPI/UpdateConfig"
)

// SystemAPIClient is the client API for SystemAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemAPIClient interface {
	GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemConfigData, error)
	UpdateConfig(ctx context.Context, in *SystemConfigData, opts ...grpc.CallOption) (*Empty, error)
}

type systemAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemAPIClient(cc grpc.ClientConnInterface) SystemAPIClient {
	return &systemAPIClient{cc}
}

func (c *systemAPIClient) GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemConfigData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemConfigData)
	err := c.cc.Invoke(ctx, SystemAPI_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAPIClient) UpdateConfig(ctx context.Context, in *SystemConfigData, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SystemAPI_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemAPIServer is the server API for SystemAPI service.
// All implementations must embed UnimplementedSystemAPIServer
// for forward compatibility.
type SystemAPIServer interface {
	GetConfig(context.Context, *Empty) (*SystemConfigData, error)
	UpdateConfig(context.Context, *SystemConfigData) (*Empty, error)
	mustEmbedUnimplementedSystemAPIServer()
}

// UnimplementedSystemAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemAPIServer struct{}

func (UnimplementedSystemAPIServer) GetConfig(context.Context, *Empty) (*SystemConfigData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedSystemAPIServer) UpdateConfig(context.Context, *SystemConfigData) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedSystemAPIServer) mustEmbedUnimplementedSystemAPIServer() {}
func (UnimplementedSystemAPIServer) testEmbeddedByValue()                   {}

// UnsafeSystemAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemAPIServer will
// result in compilation errors.
type UnsafeSystemAPIServer interface {
	mustEmbedUnimplementedSystemAPIServer()
}

func RegisterSystemAPIServer(s grpc.ServiceRegistrar, srv SystemAPIServer) {
	// If the following call pancis, it indicates UnimplementedSystemAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemAPI_ServiceDesc, srv)
}

func _SystemAPI_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAPIServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAPI_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAPIServer).GetConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAPI_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemConfigData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAPIServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAPI_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAPIServer).UpdateConfig(ctx, req.(*SystemConfigData))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemAPI_ServiceDesc is the grpc.ServiceDesc for SystemAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.SystemAPI",
	HandlerType: (*SystemAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _SystemAPI_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _SystemAPI_UpdateConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/core/core.proto",
}

const (
	StatsAPI_GetUserStats_FullMethodName = "/core.StatsAPI/GetUserStats"
)

// StatsAPIClient is the client API for StatsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsAPIClient interface {
	GetUserStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserStatsResponse, error)
}

type statsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsAPIClient(cc grpc.ClientConnInterface) StatsAPIClient {
	return &statsAPIClient{cc}
}

func (c *statsAPIClient) GetUserStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserStatsResponse)
	err := c.cc.Invoke(ctx, StatsAPI_GetUserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsAPIServer is the server API for StatsAPI service.
// All implementations must embed UnimplementedStatsAPIServer
// for forward compatibility.
type StatsAPIServer interface {
	GetUserStats(context.Context, *Empty) (*UserStatsResponse, error)
	mustEmbedUnimplementedStatsAPIServer()
}

// UnimplementedStatsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsAPIServer struct{}

func (UnimplementedStatsAPIServer) GetUserStats(context.Context, *Empty) (*UserStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserStats not implemented")
}
func (UnimplementedStatsAPIServer) mustEmbedUnimplementedStatsAPIServer() {}
func (UnimplementedStatsAPIServer) testEmbeddedByValue()                  {}

// UnsafeStatsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsAPIServer will
// result in compilation errors.
type UnsafeStatsAPIServer interface {
	mustEmbedUnimplementedStatsAPIServer()
}

func RegisterStatsAPIServer(s grpc.ServiceRegistrar, srv StatsAPIServer) {
	// If the following call pancis, it indicates UnimplementedStatsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatsAPI_ServiceDesc, srv)
}

func _StatsAPI_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsAPIServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsAPI_GetUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsAPIServer).GetUserStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsAPI_ServiceDesc is the grpc.ServiceDesc for StatsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.StatsAPI",
	HandlerType: (*StatsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserStats",
			Handler:    _StatsAPI_GetUserStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/core/core.proto",
}
