// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContainerAPI_CreateContainer_FullMethodName   = "/core.ContainerAPI/CreateContainer"
	ContainerAPI_StartContainer_FullMethodName    = "/core.ContainerAPI/StartContainer"
	ContainerAPI_StopContainer_FullMethodName     = "/core.ContainerAPI/StopContainer"
	ContainerAPI_DeleteContainer_FullMethodName   = "/core.ContainerAPI/DeleteContainer"
	ContainerAPI_GetUserContainers_FullMethodName = "/core.ContainerAPI/GetUserContainers"
	ContainerAPI_ExposeContainer_FullMethodName   = "/core.ContainerAPI/ExposeContainer"
)

// ContainerAPIClient is the client API for ContainerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContainerAPIClient interface {
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error)
	StartContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error)
	StopContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserContainers(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*ContainerListResponse, error)
	ExposeContainer(ctx context.Context, in *ExposeRequest, opts ...grpc.CallOption) (*Empty, error)
}

type containerAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerAPIClient(cc grpc.ClientConnInterface) ContainerAPIClient {
	return &containerAPIClient{cc}
}

func (c *containerAPIClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContainerResponse)
	err := c.cc.Invoke(ctx, ContainerAPI_CreateContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerAPIClient) StartContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ContainerAPI_StartContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerAPIClient) StopContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ContainerAPI_StopContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerAPIClient) DeleteContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ContainerAPI_DeleteContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerAPIClient) GetUserContainers(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*ContainerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainerListResponse)
	err := c.cc.Invoke(ctx, ContainerAPI_GetUserContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerAPIClient) ExposeContainer(ctx context.Context, in *ExposeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ContainerAPI_ExposeContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerAPIServer is the server API for ContainerAPI service.
// All implementations must embed UnimplementedContainerAPIServer
// for forward compatibility.
type ContainerAPIServer interface {
	CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error)
	StartContainer(context.Context, *ContainerActionRequest) (*Empty, error)
	StopContainer(context.Context, *ContainerActionRequest) (*Empty, error)
	DeleteContainer(context.Context, *ContainerActionRequest) (*Empty, error)
	GetUserContainers(context.Context, *GetUserRequest) (*ContainerListResponse, error)
	ExposeContainer(context.Context, *ExposeRequest) (*Empty, error)
	mustEmbedUnimplementedContainerAPIServer()
}

// UnimplementedContainerAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContainerAPIServer struct{}

func (UnimplementedContainerAPIServer) CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateContainer not implemented")
}
func (UnimplementedContainerAPIServer) StartContainer(context.Context, *ContainerActionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StartContainer not implemented")
}
func (UnimplementedContainerAPIServer) StopContainer(context.Context, *ContainerActionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopContainer not implemented")
}
func (UnimplementedContainerAPIServer) DeleteContainer(context.Context, *ContainerActionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteContainer not implemented")
}
func (UnimplementedContainerAPIServer) GetUserContainers(context.Context, *GetUserRequest) (*ContainerListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserContainers not implemented")
}
func (UnimplementedContainerAPIServer) ExposeContainer(context.Context, *ExposeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ExposeContainer not implemented")
}
func (UnimplementedContainerAPIServer) mustEmbedUnimplementedContainerAPIServer() {}
func (UnimplementedContainerAPIServer) testEmbeddedByValue()                      {}

// UnsafeContainerAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerAPIServer will
// result in compilation errors.
type UnsafeContainerAPIServer interface {
	mustEmbedUnimplementedContainerAPIServer()
}

func RegisterContainerAPIServer(s grpc.ServiceRegistrar, srv ContainerAPIServer) {
	// If the following call panics, it indicates UnimplementedContainerAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContainerAPI_ServiceDesc, srv)
}

func _ContainerAPI_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_CreateContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerAPI_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).StartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_StartContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).StartContainer(ctx, req.(*ContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerAPI_StopContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).StopContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_StopContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).StopContainer(ctx, req.(*ContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerAPI_DeleteContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).DeleteContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_DeleteContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).DeleteContainer(ctx, req.(*ContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerAPI_GetUserContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).GetUserContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_GetUserContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).GetUserContainers(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerAPI_ExposeContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAPIServer).ExposeContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAPI_ExposeContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAPIServer).ExposeContainer(ctx, req.(*ExposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContainerAPI_ServiceDesc is the grpc.ServiceDesc for ContainerAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.ContainerAPI",
	HandlerType: (*ContainerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContainer",
			Handler:    _ContainerAPI_CreateContainer_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _ContainerAPI_StartContainer_Handler,
		},
		{
			MethodName: "StopContainer",
			Handler:    _ContainerAPI_StopContainer_Handler,
		},
		{
			MethodName: "DeleteContainer",
			Handler:    _ContainerAPI_DeleteContainer_Handler,
		},
		{
			MethodName: "GetUserContainers",
			Handler:    _ContainerAPI_GetUserContainers_Handler,
		},
		{
			MethodName: "ExposeContainer",
			Handler:    _ContainerAPI_ExposeContainer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}

const (
	ImageAPI_GetUserImages_FullMethodName       = "/core.ImageAPI/GetUserImages"
	ImageAPI_DeleteImage_FullMethodName         = "/core.ImageAPI/DeleteImage"
	ImageAPI_InitBuildRecord_FullMethodName     = "/core.ImageAPI/InitBuildRecord"
	ImageAPI_CompleteBuildRecord_FullMethodName = "/core.ImageAPI/CompleteBuildRecord"
	ImageAPI_GetUserBuilds_FullMethodName       = "/core.ImageAPI/GetUserBuilds"
	ImageAPI_DeleteBuild_FullMethodName         = "/core.ImageAPI/DeleteBuild"
)

// ImageAPIClient is the client API for ImageAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageAPIClient interface {
	GetUserImages(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*ImageListResponse, error)
	DeleteImage(ctx context.Context, in *ImageActionRequest, opts ...grpc.CallOption) (*Empty, error)
	InitBuildRecord(ctx context.Context, in *InitBuildRequest, opts ...grpc.CallOption) (*InitBuildResponse, error)
	CompleteBuildRecord(ctx context.Context, in *CompleteBuildRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserBuilds(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*BuildListResponse, error)
	DeleteBuild(ctx context.Context, in *BuildActionRequest, opts ...grpc.CallOption) (*Empty, error)
}

type imageAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewImageAPIClient(cc grpc.ClientConnInterface) ImageAPIClient {
	return &imageAPIClient{cc}
}

func (c *imageAPIClient) GetUserImages(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*ImageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageListResponse)
	err := c.cc.Invoke(ctx, ImageAPI_GetUserImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) DeleteImage(ctx context.Context, in *ImageActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ImageAPI_DeleteImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) InitBuildRecord(ctx context.Context, in *InitBuildRequest, opts ...grpc.CallOption) (*InitBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitBuildResponse)
	err := c.cc.Invoke(ctx, ImageAPI_InitBuildRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) CompleteBuildRecord(ctx context.Context, in *CompleteBuildRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ImageAPI_CompleteBuildRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) GetUserBuilds(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*BuildListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildListResponse)
	err := c.cc.Invoke(ctx, ImageAPI_GetUserBuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageAPIClient) DeleteBuild(ctx context.Context, in *BuildActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ImageAPI_DeleteBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageAPIServer is the server API for ImageAPI service.
// All implementations must embed UnimplementedImageAPIServer
// for forward compatibility.
type ImageAPIServer interface {
	GetUserImages(context.Context, *GetUserRequest) (*ImageListResponse, error)
	DeleteImage(context.Context, *ImageActionRequest) (*Empty, error)
	InitBuildRecord(context.Context, *InitBuildRequest) (*InitBuildResponse, error)
	CompleteBuildRecord(context.Context, *CompleteBuildRequest) (*Empty, error)
	GetUserBuilds(context.Context, *GetUserRequest) (*BuildListResponse, error)
	DeleteBuild(context.Context, *BuildActionRequest) (*Empty, error)
	mustEmbedUnimplementedImageAPIServer()
}

// UnimplementedImageAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageAPIServer struct{}

func (UnimplementedImageAPIServer) GetUserImages(context.Context, *GetUserRequest) (*ImageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserImages not implemented")
}
func (UnimplementedImageAPIServer) DeleteImage(context.Context, *ImageActionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteImage not implemented")
}
func (UnimplementedImageAPIServer) InitBuildRecord(context.Context, *InitBuildRequest) (*InitBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitBuildRecord not implemented")
}
func (UnimplementedImageAPIServer) CompleteBuildRecord(context.Context, *CompleteBuildRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteBuildRecord not implemented")
}
func (UnimplementedImageAPIServer) GetUserBuilds(context.Context, *GetUserRequest) (*BuildListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserBuilds not implemented")
}
func (UnimplementedImageAPIServer) DeleteBuild(context.Context, *BuildActionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBuild not implemented")
}
func (UnimplementedImageAPIServer) mustEmbedUnimplementedImageAPIServer() {}
func (UnimplementedImageAPIServer) testEmbeddedByValue()                  {}

// UnsafeImageAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageAPIServer will
// result in compilation errors.
type UnsafeImageAPIServer interface {
	mustEmbedUnimplementedImageAPIServer()
}

func RegisterImageAPIServer(s grpc.ServiceRegistrar, srv ImageAPIServer) {
	// If the following call panics, it indicates UnimplementedImageAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageAPI_ServiceDesc, srv)
}

func _ImageAPI_GetUserImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).GetUserImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_GetUserImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).GetUserImages(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_DeleteImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).DeleteImage(ctx, req.(*ImageActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_InitBuildRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).InitBuildRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_InitBuildRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).InitBuildRecord(ctx, req.(*InitBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_CompleteBuildRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).CompleteBuildRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_CompleteBuildRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).CompleteBuildRecord(ctx, req.(*CompleteBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_GetUserBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).GetUserBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_GetUserBuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).GetUserBuilds(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageAPI_DeleteBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageAPIServer).DeleteBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageAPI_DeleteBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageAPIServer).DeleteBuild(ctx, req.(*BuildActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageAPI_ServiceDesc is the grpc.ServiceDesc for ImageAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.ImageAPI",
	HandlerType: (*ImageAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserImages",
			Handler:    _ImageAPI_GetUserImages_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _ImageAPI_DeleteImage_Handler,
		},
		{
			MethodName: "InitBuildRecord",
			Handler:    _ImageAPI_InitBuildRecord_Handler,
		},
		{
			MethodName: "CompleteBuildRecord",
			Handler:    _ImageAPI_CompleteBuildRecord_Handler,
		},
		{
			MethodName: "GetUserBuilds",
			Handler:    _ImageAPI_GetUserBuilds_Handler,
		},
		{
			MethodName: "DeleteBuild",
			Handler:    _ImageAPI_DeleteBuild_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}

const (
	VolumeAPI_CreateVolume_FullMethodName   = "/core.VolumeAPI/CreateVolume"
	VolumeAPI_DeleteVolume_FullMethodName   = "/core.VolumeAPI/DeleteVolume"
	VolumeAPI_GetUserVolumes_FullMethodName = "/core.VolumeAPI/GetUserVolumes"
)

// VolumeAPIClient is the client API for VolumeAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VolumeAPIClient interface {
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	DeleteVolume(ctx context.Context, in *VolumeActionRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserVolumes(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*VolumeListResponse, error)
}

type volumeAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewVolumeAPIClient(cc grpc.ClientConnInterface) VolumeAPIClient {
	return &volumeAPIClient{cc}
}

func (c *volumeAPIClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, VolumeAPI_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeAPIClient) DeleteVolume(ctx context.Context, in *VolumeActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VolumeAPI_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeAPIClient) GetUserVolumes(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*VolumeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VolumeListResponse)
	err := c.cc.Invoke(ctx, VolumeAPI_GetUserVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumeAPIServer is the server API for VolumeAPI service.
// All implementations must embed UnimplementedVolumeAPIServer
// for forward compatibility.
type VolumeAPIServer interface {
	CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	DeleteVolume(context.Context, *VolumeActionRequest) (*Empty, error)
	GetUserVolumes(context.Context, *GetUserRequest) (*VolumeListResponse, error)
	mustEmbedUnimplementedVolumeAPIServer()
}

// UnimplementedVolumeAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolumeAPIServer struct{}

func (UnimplementedVolumeAPIServer) CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedVolumeAPIServer) DeleteVolume(context.Context, *VolumeActionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedVolumeAPIServer) GetUserVolumes(context.Context, *GetUserRequest) (*VolumeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserVolumes not implemented")
}
func (UnimplementedVolumeAPIServer) mustEmbedUnimplementedVolumeAPIServer() {}
func (UnimplementedVolumeAPIServer) testEmbeddedByValue()                   {}

// UnsafeVolumeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolumeAPIServer will
// result in compilation errors.
type UnsafeVolumeAPIServer interface {
	mustEmbedUnimplementedVolumeAPIServer()
}

func RegisterVolumeAPIServer(s grpc.ServiceRegistrar, srv VolumeAPIServer) {
	// If the following call panics, it indicates UnimplementedVolumeAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolumeAPI_ServiceDesc, srv)
}

func _VolumeAPI_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeAPIServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeAPI_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeAPIServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeAPI_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeAPIServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeAPI_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeAPIServer).DeleteVolume(ctx, req.(*VolumeActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeAPI_GetUserVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeAPIServer).GetUserVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeAPI_GetUserVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeAPIServer).GetUserVolumes(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VolumeAPI_ServiceDesc is the grpc.ServiceDesc for VolumeAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolumeAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.VolumeAPI",
	HandlerType: (*VolumeAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVolume",
			Handler:    _VolumeAPI_CreateVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _VolumeAPI_DeleteVolume_Handler,
		},
		{
			MethodName: "GetUserVolumes",
			Handler:    _VolumeAPI_GetUserVolumes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}
