package grpcclient

import (
	"context"

	coreapi "github.com/callmerussell04/docker-cloud-manager/api/core"
	"github.com/callmerussell04/docker-cloud-manager/internal/gateway/model"
	"github.com/callmerussell04/docker-cloud-manager/pkg/grpcerrors"
)

func (c *CoreClient) GetSystemConfig(ctx context.Context) (model.SystemConfig, error) {
	resp, err := c.systemAPI.GetConfig(ctx, &coreapi.Empty{})
	if err != nil {
		return model.SystemConfig{}, grpcerrors.FromGRPC(err)
	}
	return systemConfigFromProto(resp), nil
}

func (c *CoreClient) UpdateSystemConfig(ctx context.Context, req model.SystemConfig) error {
	_, err := c.systemAPI.UpdateConfig(ctx, systemConfigToProto(req))
	if err != nil {
		return grpcerrors.FromGRPC(err)
	}
	return nil
}

func systemConfigFromProto(data *coreapi.SystemConfigData) model.SystemConfig {
	return model.SystemConfig{
		BaseDomain:                           data.GetBaseDomain(),
		DefaultMemoryReservationBytes:        data.GetDefaultMemoryReservationBytes(),
		ReservedSystemMemoryBytes:            data.GetReservedSystemMemoryBytes(),
		OvercommitFactor:                     data.GetOvercommitFactor(),
		MaxBurstMultiplier:                   data.GetMaxBurstMultiplier(),
		DefaultCPUReservationMillicores:      data.GetDefaultCpuReservationMillicores(),
		ReservedSystemCPUMillicores:          data.GetReservedSystemCpuMillicores(),
		CPUOvercommitFactor:                  data.GetCpuOvercommitFactor(),
		MaxCPUBurstMultiplier:                data.GetMaxCpuBurstMultiplier(),
		ContainerCPUPeriod:                   data.GetContainerCpuPeriod(),
		DefaultCpuShares:                     data.GetDefaultCpuShares(),
		HighLoadCpuShares:                    data.GetHighLoadCpuShares(),
		HighLoadContainerCount:               int(data.GetHighLoadContainerCount()),
		ContainerStopTimeout:                 int(data.GetContainerStopTimeout()),
		MaxLogSize:                           data.GetMaxLogSize(),
		MaxLogFiles:                          data.GetMaxLogFiles(),
		ContainerDiskQuota:                   data.GetContainerDiskQuota(),
		ReservedDomainPrefixes:               data.GetReservedDomainPrefixes(),
		BlockedDomainPrefixPatterns:          data.GetBlockedDomainPrefixPatterns(),
		MaxVolumesPerUser:                    int(data.GetMaxVolumesPerUser()),
		MaxContainersPerUser:                 int(data.GetMaxContainersPerUser()),
		ContainerTtlHours:                    data.GetContainerTtlHours(),
		ContainerPidsLimit:                   data.GetContainerPidsLimit(),
		ContainerMemorySwapMultiplier:        data.GetContainerMemorySwapMultiplier(),
		ImageBuildsEnabled:                   data.GetImageBuildsEnabled(),
		BuildMemoryBytes:                     data.GetBuildMemoryBytes(),
		BuildCpuQuota:                        data.GetBuildCpuQuota(),
		BuildCpuPeriod:                       data.GetBuildCpuPeriod(),
		BuildMemorySwapMultiplier:            data.GetBuildMemorySwapMultiplier(),
		BuildPidsLimit:                       data.GetBuildPidsLimit(),
		KanikoImage:                          data.GetKanikoImage(),
		MaxBuildTimeMinutes:                  data.GetMaxBuildTimeMinutes(),
		MaxConcurrentBuilds:                  int(data.GetMaxConcurrentBuilds()),
		MaxUploadSizeBytes:                   data.GetMaxUploadSizeBytes(),
		MaxArchiveSizeBytes:                  data.GetMaxArchiveSizeBytes(),
		MaxUnpackedSizeBytes:                 data.GetMaxUnpackedSizeBytes(),
		MaxBuildLogSizeBytes:                 data.GetMaxBuildLogSizeBytes(),
		BuildCancelPollIntervalSeconds:       data.GetBuildCancelPollIntervalSeconds(),
		TtlWorkerIntervalSeconds:             data.GetTtlWorkerIntervalSeconds(),
		GcWorkerIntervalMinutes:              data.GetGcWorkerIntervalMinutes(),
		StaleBuildTimeoutMinutes:             data.GetStaleBuildTimeoutMinutes(),
		EventSyncIntervalSeconds:             data.GetEventSyncIntervalSeconds(),
		EventReconnectDelaySeconds:           data.GetEventReconnectDelaySeconds(),
		BuildOutboxIntervalSeconds:           data.GetBuildOutboxIntervalSeconds(),
		BuildOutboxBatchSize:                 int(data.GetBuildOutboxBatchSize()),
		ReportsUsageSnapshotIntervalSeconds:  data.GetReportsUsageSnapshotIntervalSeconds(),
		ContainerCreateWorkerCount:           int(data.GetContainerCreateWorkerCount()),
		ContainerCreateMaxAttempts:           int(data.GetContainerCreateMaxAttempts()),
		ContainerCreateTimeoutMinutes:        data.GetContainerCreateTimeoutMinutes(),
		MaxQueuedContainerCreatesPerUser:     int(data.GetMaxQueuedContainerCreatesPerUser()),
		ContainerCreateOutboxIntervalSeconds: data.GetContainerCreateOutboxIntervalSeconds(),
		ContainerCreateOutboxBatchSize:       int(data.GetContainerCreateOutboxBatchSize()),
		MaxStagedSourceBytesPerUser:          data.GetMaxStagedSourceBytesPerUser(),
		MaxQueuedBuildsPerUser:               int(data.GetMaxQueuedBuildsPerUser()),
		ComposeUploadMaxBytes:                data.GetComposeUploadMaxBytes(),
		ComposePipelineTimeoutMinutes:        data.GetComposePipelineTimeoutMinutes(),
		ComposeDeployWorkerCount:             int(data.GetComposeDeployWorkerCount()),
		ComposeOutboxIntervalSeconds:         data.GetComposeOutboxIntervalSeconds(),
		ComposeOutboxBatchSize:               int(data.GetComposeOutboxBatchSize()),
		ComposeDeployMaxAttempts:             int(data.GetComposeDeployMaxAttempts()),
		MaxQueuedComposeDeploysPerUser:       int(data.GetMaxQueuedComposeDeploysPerUser()),
		ComposeBuildPollIntervalSeconds:      data.GetComposeBuildPollIntervalSeconds(),
		ComposeDependencyWaitTimeoutMinutes:  data.GetComposeDependencyWaitTimeoutMinutes(),
		ComposeDependencyPollIntervalSeconds: data.GetComposeDependencyPollIntervalSeconds(),
		ComposeCoordinatorIntervalSeconds:    data.GetComposeCoordinatorIntervalSeconds(),
		HostMinFreeDiskBytes:                 data.GetHostMinFreeDiskBytes(),
		GitSourcesEnabled:                    data.GetGitSourcesEnabled(),
		GitAllowedHosts:                      data.GetGitAllowedHosts(),
		GitCloneTimeoutSeconds:               data.GetGitCloneTimeoutSeconds(),
		GitMaxRepositoryBytes:                data.GetGitMaxRepositoryBytes(),
		TelemetryMaxLogTailLines:             int(data.GetTelemetryMaxLogTailLines()),
		TelemetryMaxLogStreamsPerUser:        int(data.GetTelemetryMaxLogStreamsPerUser()),
		TelemetryMaxTerminalSessionsPerUser:  int(data.GetTelemetryMaxTerminalSessionsPerUser()),
		TelemetryTerminalIdleTimeoutSeconds:  data.GetTelemetryTerminalIdleTimeoutSeconds(),
		TelemetryTerminalMaxDurationSeconds:  data.GetTelemetryTerminalMaxDurationSeconds(),
		TelemetryAllowedExecCommands:         data.GetTelemetryAllowedExecCommands(),
		TelemetryMaxCommandArgs:              int(data.GetTelemetryMaxCommandArgs()),
		TelemetryMaxCommandArgBytes:          int(data.GetTelemetryMaxCommandArgBytes()),
		TelemetryWSReadLimitBytes:            data.GetTelemetryWsReadLimitBytes(),
	}
}

func systemConfigToProto(data model.SystemConfig) *coreapi.SystemConfigData {
	return &coreapi.SystemConfigData{
		BaseDomain:                           data.BaseDomain,
		DefaultMemoryReservationBytes:        data.DefaultMemoryReservationBytes,
		ReservedSystemMemoryBytes:            data.ReservedSystemMemoryBytes,
		OvercommitFactor:                     data.OvercommitFactor,
		MaxBurstMultiplier:                   data.MaxBurstMultiplier,
		DefaultCpuReservationMillicores:      data.DefaultCPUReservationMillicores,
		ReservedSystemCpuMillicores:          data.ReservedSystemCPUMillicores,
		CpuOvercommitFactor:                  data.CPUOvercommitFactor,
		MaxCpuBurstMultiplier:                data.MaxCPUBurstMultiplier,
		ContainerCpuPeriod:                   data.ContainerCPUPeriod,
		DefaultCpuShares:                     data.DefaultCpuShares,
		HighLoadCpuShares:                    data.HighLoadCpuShares,
		HighLoadContainerCount:               int32(data.HighLoadContainerCount),
		ContainerStopTimeout:                 int32(data.ContainerStopTimeout),
		MaxLogSize:                           data.MaxLogSize,
		MaxLogFiles:                          data.MaxLogFiles,
		ContainerDiskQuota:                   data.ContainerDiskQuota,
		ReservedDomainPrefixes:               data.ReservedDomainPrefixes,
		BlockedDomainPrefixPatterns:          data.BlockedDomainPrefixPatterns,
		MaxVolumesPerUser:                    int32(data.MaxVolumesPerUser),
		MaxContainersPerUser:                 int32(data.MaxContainersPerUser),
		ContainerTtlHours:                    data.ContainerTtlHours,
		ContainerPidsLimit:                   data.ContainerPidsLimit,
		ContainerMemorySwapMultiplier:        data.ContainerMemorySwapMultiplier,
		ImageBuildsEnabled:                   data.ImageBuildsEnabled,
		BuildMemoryBytes:                     data.BuildMemoryBytes,
		BuildCpuQuota:                        data.BuildCpuQuota,
		BuildCpuPeriod:                       data.BuildCpuPeriod,
		BuildMemorySwapMultiplier:            data.BuildMemorySwapMultiplier,
		BuildPidsLimit:                       data.BuildPidsLimit,
		KanikoImage:                          data.KanikoImage,
		MaxBuildTimeMinutes:                  data.MaxBuildTimeMinutes,
		MaxConcurrentBuilds:                  int32(data.MaxConcurrentBuilds),
		MaxUploadSizeBytes:                   data.MaxUploadSizeBytes,
		MaxArchiveSizeBytes:                  data.MaxArchiveSizeBytes,
		MaxUnpackedSizeBytes:                 data.MaxUnpackedSizeBytes,
		MaxBuildLogSizeBytes:                 data.MaxBuildLogSizeBytes,
		BuildCancelPollIntervalSeconds:       data.BuildCancelPollIntervalSeconds,
		TtlWorkerIntervalSeconds:             data.TtlWorkerIntervalSeconds,
		GcWorkerIntervalMinutes:              data.GcWorkerIntervalMinutes,
		StaleBuildTimeoutMinutes:             data.StaleBuildTimeoutMinutes,
		EventSyncIntervalSeconds:             data.EventSyncIntervalSeconds,
		EventReconnectDelaySeconds:           data.EventReconnectDelaySeconds,
		BuildOutboxIntervalSeconds:           data.BuildOutboxIntervalSeconds,
		BuildOutboxBatchSize:                 int32(data.BuildOutboxBatchSize),
		ReportsUsageSnapshotIntervalSeconds:  data.ReportsUsageSnapshotIntervalSeconds,
		ContainerCreateWorkerCount:           int32(data.ContainerCreateWorkerCount),
		ContainerCreateMaxAttempts:           int32(data.ContainerCreateMaxAttempts),
		ContainerCreateTimeoutMinutes:        data.ContainerCreateTimeoutMinutes,
		MaxQueuedContainerCreatesPerUser:     int32(data.MaxQueuedContainerCreatesPerUser),
		ContainerCreateOutboxIntervalSeconds: data.ContainerCreateOutboxIntervalSeconds,
		ContainerCreateOutboxBatchSize:       int32(data.ContainerCreateOutboxBatchSize),
		MaxStagedSourceBytesPerUser:          data.MaxStagedSourceBytesPerUser,
		MaxQueuedBuildsPerUser:               int32(data.MaxQueuedBuildsPerUser),
		ComposeUploadMaxBytes:                data.ComposeUploadMaxBytes,
		ComposePipelineTimeoutMinutes:        data.ComposePipelineTimeoutMinutes,
		ComposeDeployWorkerCount:             int32(data.ComposeDeployWorkerCount),
		ComposeOutboxIntervalSeconds:         data.ComposeOutboxIntervalSeconds,
		ComposeOutboxBatchSize:               int32(data.ComposeOutboxBatchSize),
		ComposeDeployMaxAttempts:             int32(data.ComposeDeployMaxAttempts),
		MaxQueuedComposeDeploysPerUser:       int32(data.MaxQueuedComposeDeploysPerUser),
		ComposeBuildPollIntervalSeconds:      data.ComposeBuildPollIntervalSeconds,
		ComposeDependencyWaitTimeoutMinutes:  data.ComposeDependencyWaitTimeoutMinutes,
		ComposeDependencyPollIntervalSeconds: data.ComposeDependencyPollIntervalSeconds,
		ComposeCoordinatorIntervalSeconds:    data.ComposeCoordinatorIntervalSeconds,
		HostMinFreeDiskBytes:                 data.HostMinFreeDiskBytes,
		GitSourcesEnabled:                    data.GitSourcesEnabled,
		GitAllowedHosts:                      data.GitAllowedHosts,
		GitCloneTimeoutSeconds:               data.GitCloneTimeoutSeconds,
		GitMaxRepositoryBytes:                data.GitMaxRepositoryBytes,
		TelemetryMaxLogTailLines:             int32(data.TelemetryMaxLogTailLines),
		TelemetryMaxLogStreamsPerUser:        int32(data.TelemetryMaxLogStreamsPerUser),
		TelemetryMaxTerminalSessionsPerUser:  int32(data.TelemetryMaxTerminalSessionsPerUser),
		TelemetryTerminalIdleTimeoutSeconds:  data.TelemetryTerminalIdleTimeoutSeconds,
		TelemetryTerminalMaxDurationSeconds:  data.TelemetryTerminalMaxDurationSeconds,
		TelemetryAllowedExecCommands:         data.TelemetryAllowedExecCommands,
		TelemetryMaxCommandArgs:              int32(data.TelemetryMaxCommandArgs),
		TelemetryMaxCommandArgBytes:          int32(data.TelemetryMaxCommandArgBytes),
		TelemetryWsReadLimitBytes:            data.TelemetryWSReadLimitBytes,
	}
}
